### ISSUE TITLE
Support modify column/add bloom filter/add bitmap index for table with primary key

### ISSUE THREAD

**Issue by Linkerist** [StarRocks/starrocks#1265]
## Feature request

**Is your feature request related to a problem? Please describe.**

### Repetition steps
```SQL
create database test_primary_table_operation_1634044922030;
use test_primary_table_operation_1634044922030;
select connection_id();
CREATE TABLE `primary_table_without_null` ( `k1` date NOT NULL, `k2` datetime NOT NULL, `k3` string NOT NULL, `k4` string NOT NULL, `k5` boolean NOT NULL, `v1` tinyint NOT NULL, `v2` smallint NOT NULL, `v3` int NOT NULL, `v4` bigint NOT NULL, `v5` largeint NOT NULL, `v6` float NOT NULL, `v7` double NOT NULL, `v8` decimal(27,9) NOT NULL ) ENGINE=OLAP PRIMARY KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3 PROPERTIES ( "replication_num" = "1", "storage_format" = "v2" );
curl --location-trusted -u root: -T /home/disk1/jenkins/workspace/test/branch_test/push/dorisdb-test/lib/../common/data/basic_types_data_without_null -XPUT -H label:stream_load_1634044922051 -H columns:__op='upsert' http://ip:port/api/test_primary_table_operation_1634044922030/primary_table_without_null/_stream_load

ALTER TABLE primary_table_without_null SET ("bloom_filter_columns"="k3");

show alter table column;

SELECT 
                   SUM(v2),
                   SUM(v3),
                   MAX(v4),
                   MAX(v5)
                 FROM primary_table_without_null 
                 WHERE k3 = 'guangzhou';
```
then check the profile:
```
Query:
  Summary:
     - Query ID: 74be520c-2b5f-11ec-a9ec-00163e10c9d6
     - Start Time: 2021-10-12 21:22:32
     - End Time: 2021-10-12 21:22:32
     - Total: 9ms
     - Query Type: Query
     - Query State: EOF
     - StarRocks Version: UNKNOWN
     - User: root
     - Default Db: default_cluster:test_primary_table_operation_1634044922030
     - Sql Statement: SELECT 
                   SUM(v2),
                   SUM(v3),
                   MAX(v4),
                   MAX(v5)
                 FROM primary_table_without_null 
                 WHERE k3 = 'guangzhou'
  Execution Profile 74be520c-2b5f-11ec-a9ec-00163e10c9d6:(Active: 9.572ms[9572953ns], % non-child: 100.00%)
    Fragment 0:
      Instance 74be520c-2b5f-11ec-a9ec-00163e10c9da (host=TNetworkAddress(hostname:172.26.92.152, port:9560)):(Active: 7.410ms[7410857ns], % non-child: 0.29%)
         - AverageThreadTokens: 0.00
         - MemoryLimit: 2.00 GB
         - PeakMemoryUsage: 4.00 KB
         - PeakReservation: 0.00 
         - PeakUsedReservation: 0.00 
         - RowsProduced: 1
        BlockMgr:
           - BlockWritesOutstanding: 0
           - BlocksCreated: 0
           - BlocksRecycled: 0
           - BufferedPins: 0
           - BytesWritten: 0.00 
           - MaxBlockSize: 8.00 MB
           - TotalBufferWaitTime: 0ns
           - TotalReadBlockTime: 0ns
        DataBufferSender (dst_fragment_instance_id=74be520c-2b5f-11ec-a9ec-00163e10c9da):
           - AppendBatchTime: 3.984us
             - ResultRendTime: 29.114us
             - TupleConvertTime: 2.545us
           - NumSentRows: 1
        AGGREGATION_NODE (id=3):(Active: 7.382ms[7382919ns], % non-child: 1.08%)
           - AggregateFunctions: max(10: v5), sum(7: v2), sum(8: v3), max(9: v4)
           - AggComputeTime: 62.412us
           - ExprComputeTime: 5.163us
           - ExprReleaseTime: 8.518us
           - GetResultsTime: 4.804us
           - HashTableSize: 0
           - InputRowCount: 16.384K (16384)
           - PassThroughRowCount: 0
           - PeakMemoryUsage: 4.00 KB
           - ResultAggAppendTime: 0ns
           - ResultGroupByAppendTime: 0ns
           - ResultIteratorTime: 0ns
           - RowsReturned: 1
           - RowsReturnedRate: 135
           - StreamingTime: 0ns
          EXCHANGE_NODE (id=2):(Active: 7.279ms[7279775ns], % non-child: 76.05%)
             - BytesReceived: 235.19 KB
             - ConvertRowBatchTime: 0ns
             - DataArrivalWaitTime: 0ns
             - DecompressRowBatchTimer: 351.32us
             - DeserializeChunkMetaTimer: 0ns
             - DeserializeRowBatchTimer: 193.641us
             - FirstBatchArrivalWaitTime: 0ns
             - PeakMemoryUsage: 0.00 
             - RequestReceived: 3.00 B
             - RowsReturned: 16.384K (16384)
             - RowsReturnedRate: 2.250619M /sec
             - SenderTotalTime: 562.19us
             - SenderWaitLockTime: 494ns
             - SendersBlockedTotalTimer(*): 0ns
    Fragment 1:
      Instance 74be520c-2b5f-11ec-a9ec-00163e10c9d9 (host=TNetworkAddress(hostname:172.26.92.141, port:9560)):(Active: 6.651ms[6651555ns], % non-child: 0.00%)
         - AverageThreadTokens: 0.00
         - MemoryLimit: 2.00 GB
         - PeakMemoryUsage: 1.17 MB
         - PeakReservation: 0.00 
         - PeakUsedReservation: 0.00 
         - RowsProduced: 5.447K (5447)
        BlockMgr:
           - BlockWritesOutstanding: 0
           - BlocksCreated: 0
           - BlocksRecycled: 0
           - BufferedPins: 0
           - BytesWritten: 0.00 
           - MaxBlockSize: 8.00 MB
           - TotalBufferWaitTime: 0ns
           - TotalReadBlockTime: 0ns
        DataStreamSender (dst_id=2, dst_fragments=[74be520c2b5f11ec-a9ec00163e10c9da]):(Active: 1.108ms[1108066ns], % non-child: 11.57%)
           - PartType: UNPARTITIONED
           - BytesSent: 78.21 KB
           - CompressTime: 161.338us
           - IgnoreRows: 0
           - OverallThroughput: 68.92726707458496 MB/sec
           - PeakMemoryUsage: 4.00 KB
           - SendRequestTime: 67.5us
           - SerializeBatchTime: 56.20us
           - ShuffleDispatchTime: 0ns
           - ShuffleHashTime: 0ns
           - UncompressedBytes: 159.63 KB
           - WaitResponseTime: 782.364us
        PROJECT_NODE (id=1):(Active: 5.628ms[5628745ns], % non-child: 0.93%)
           - CommonSubExprComputeTime: 312ns
           - ExprComputeTime: 2.145us
           - PeakMemoryUsage: 0.00 
           - RowsReturned: 5.447K (5447)
           - RowsReturnedRate: 967.711K /sec
          OLAP_SCAN_NODE (id=0):(Active: 5.539ms[5539735ns], % non-child: 13.26%)
             - Table: primary_table_without_null
             - Rollup: primary_table_without_null
             - Predicates: 3: k3 = 'guangzhou'
             - BytesRead: 313.85 KB
             - NumDiskAccess: 0
             - PeakMemoryUsage: 1.17 MB
             - PerReadThreadRawHdfsThroughput: 0.0 /sec
             - RowsRead: 0
             - RowsReturned: 5.447K (5447)
             - RowsReturnedRate: 983.26K /sec
             - ScanTime: 4.275ms
             - ScannerThreadsInvoluntaryContextSwitches: 0
             - ScannerThreadsTotalWallClockTime: 0ns
               - MaterializeTupleTime(*): 0ns
               - ScannerThreadsSysTime: 0ns
               - ScannerThreadsUserTime: 0ns
             - ScannerThreadsVoluntaryContextSwitches: 0
             - TabletCount : 1
             - TotalRawReadTime(*): 0ns
             - TotalReadThroughput: 0.0 /sec
            SCAN:(Active: 4.270ms[4270440ns], % non-child: 44.61%)
               - CachedPagesNum: 0
               - CompressedBytesRead: 72.47 KB
               - CreateSegmentIter: 1.180ms
               - DictDecode: 84.734us
               - IOTime: 28.449us
               - LateMaterialize: 222.788us
               - PushdownPredicates: 1
               - RawRowsRead: 21.618K (21618)
               - SegmentInit: 3.833ms
                 - BitmapIndexFilter: 0ns
                 - BitmapIndexFilterRows: 0
                 - BloomFilterFilterRows: 0
                 - ShortKeyFilterRows: 0
                 - ZoneMapIndexFilterRows: 0
               - SegmentRead: 98.383us
                 - BlockFetch: 46.773us
                 - BlockFetchCount: 6
                 - BlockSeek: 40.363us
                 - BlockSeekCount: 1
                 - ChunkCopy: 1.989us
                 - DecompressT: 7.645us
                 - DelVecFilterRows: 0
                 - IndexLoad: 0ns
                 - PredFilter: 4.411us
                 - PredFilterRows: 16.171K (16171)
               - TotalPagesNum: 11
               - UncompressedBytesRead: 72.58 KB
      Instance 74be520c-2b5f-11ec-a9ec-00163e10c9d8 (host=TNetworkAddress(hostname:172.26.92.151, port:9560)):(Active: 5.586ms[5586352ns], % non-child: 0.00%)
         - AverageThreadTokens: 0.00
         - MemoryLimit: 2.00 GB
         - PeakMemoryUsage: 1.17 MB
         - PeakReservation: 0.00 
         - PeakUsedReservation: 0.00 
         - RowsProduced: 5.466K (5466)
        BlockMgr:
           - BlockWritesOutstanding: 0
           - BlocksCreated: 0
           - BlocksRecycled: 0
           - BufferedPins: 0
           - BytesWritten: 0.00 
           - MaxBlockSize: 8.00 MB
           - TotalBufferWaitTime: 0ns
           - TotalReadBlockTime: 0ns
        DataStreamSender (dst_id=2, dst_fragments=[74be520c2b5f11ec-a9ec00163e10c9da]):(Active: 1.115ms[1115327ns], % non-child: 11.65%)
           - PartType: UNPARTITIONED
           - BytesSent: 78.46 KB
           - CompressTime: 163.325us
           - IgnoreRows: 0
           - OverallThroughput: 68.69401264190674 MB/sec
           - PeakMemoryUsage: 4.00 KB
           - SendRequestTime: 73.403us
           - SerializeBatchTime: 34.219us
           - ShuffleDispatchTime: 0ns
           - ShuffleHashTime: 0ns
           - UncompressedBytes: 160.18 KB
           - WaitResponseTime: 805.265us
        PROJECT_NODE (id=1):(Active: 4.541ms[4541528ns], % non-child: 0.81%)
           - CommonSubExprComputeTime: 195ns
           - ExprComputeTime: 2.839us
           - PeakMemoryUsage: 0.00 
           - RowsReturned: 5.466K (5466)
           - RowsReturnedRate: 1.203559M /sec
          OLAP_SCAN_NODE (id=0):(Active: 4.464ms[4464315ns], % non-child: 2.60%)
             - Table: primary_table_without_null
             - Rollup: primary_table_without_null
             - Predicates: 3: k3 = 'guangzhou'
             - BytesRead: 316.19 KB
             - NumDiskAccess: 0
             - PeakMemoryUsage: 1.17 MB
             - PerReadThreadRawHdfsThroughput: 0.0 /sec
             - RowsRead: 0
             - RowsReturned: 5.466K (5466)
             - RowsReturnedRate: 1.224375M /sec
             - ScanTime: 4.219ms
             - ScannerThreadsInvoluntaryContextSwitches: 0
             - ScannerThreadsTotalWallClockTime: 0ns
               - MaterializeTupleTime(*): 0ns
               - ScannerThreadsSysTime: 0ns
               - ScannerThreadsUserTime: 0ns
             - ScannerThreadsVoluntaryContextSwitches: 0
             - TabletCount : 1
             - TotalRawReadTime(*): 0ns
             - TotalReadThroughput: 0.0 /sec
            SCAN:(Active: 4.215ms[4215401ns], % non-child: 44.03%)
               - CachedPagesNum: 0
               - CompressedBytesRead: 42.26 KB
               - CreateSegmentIter: 136.401us
               - DictDecode: 80.38us
               - IOTime: 21.960us
               - LateMaterialize: 130.356us
               - PushdownPredicates: 1
               - RawRowsRead: 22.011K (22011)
               - SegmentInit: 3.885ms
                 - BitmapIndexFilter: 0ns
                 - BitmapIndexFilterRows: 0
                 - BloomFilterFilterRows: 0
                 - ShortKeyFilterRows: 0
                 - ZoneMapIndexFilterRows: 0
               - SegmentRead: 92.680us
                 - BlockFetch: 36.424us
                 - BlockFetchCount: 7
                 - BlockSeek: 44.299us
                 - BlockSeekCount: 1
                 - ChunkCopy: 3.103us
                 - DecompressT: 8.293us
                 - DelVecFilterRows: 0
                 - IndexLoad: 0ns
                 - PredFilter: 4.49us
                 - PredFilterRows: 16.545K (16545)
               - TotalPagesNum: 8
               - UncompressedBytesRead: 42.45 KB
      Instance 74be520c-2b5f-11ec-a9ec-00163e10c9d7 (host=TNetworkAddress(hostname:172.26.92.152, port:9560)):(Active: 4.59ms[4059713ns], % non-child: 0.00%)
         - AverageThreadTokens: 0.00
         - MemoryLimit: 2.00 GB
         - PeakMemoryUsage: 1.16 MB
         - PeakReservation: 0.00 
         - PeakUsedReservation: 0.00 
         - RowsProduced: 5.471K (5471)
        BlockMgr:
           - BlockWritesOutstanding: 0
           - BlocksCreated: 0
           - BlocksRecycled: 0
           - BufferedPins: 0
           - BytesWritten: 0.00 
           - MaxBlockSize: 8.00 MB
           - TotalBufferWaitTime: 0ns
           - TotalReadBlockTime: 0ns
        DataStreamSender (dst_id=2, dst_fragments=[74be520c2b5f11ec-a9ec00163e10c9da]):(Active: 737.873us[737873ns], % non-child: 7.71%)
           - PartType: UNPARTITIONED
           - BytesSent: 78.52 KB
           - CompressTime: 162.477us
           - IgnoreRows: 0
           - OverallThroughput: 103.92444801330566 MB/sec
           - PeakMemoryUsage: 4.00 KB
           - SendRequestTime: 62.628us
           - SerializeBatchTime: 35.641us
           - ShuffleDispatchTime: 0ns
           - ShuffleHashTime: 0ns
           - UncompressedBytes: 160.33 KB
           - WaitResponseTime: 436.296us
        PROJECT_NODE (id=1):(Active: 3.391ms[3391915ns], % non-child: 0.73%)
           - CommonSubExprComputeTime: 209ns
           - ExprComputeTime: 2.360us
           - PeakMemoryUsage: 0.00 
           - RowsReturned: 5.471K (5471)
           - RowsReturnedRate: 1.612953M /sec
          OLAP_SCAN_NODE (id=0):(Active: 3.321ms[3321801ns], % non-child: 2.07%)
             - Table: primary_table_without_null
             - Rollup: primary_table_without_null
             - Predicates: 3: k3 = 'guangzhou'
             - BytesRead: 315.99 KB
             - NumDiskAccess: 0
             - PeakMemoryUsage: 1.16 MB
             - PerReadThreadRawHdfsThroughput: 0.0 /sec
             - RowsRead: 0
             - RowsReturned: 5.471K (5471)
             - RowsReturnedRate: 1.646998M /sec
             - ScanTime: 3.129ms
             - ScannerThreadsInvoluntaryContextSwitches: 0
             - ScannerThreadsTotalWallClockTime: 0ns
               - MaterializeTupleTime(*): 0ns
               - ScannerThreadsSysTime: 0ns
               - ScannerThreadsUserTime: 0ns
             - ScannerThreadsVoluntaryContextSwitches: 0
             - TabletCount : 1
             - TotalRawReadTime(*): 0ns
             - TotalReadThroughput: 0.0 /sec
            SCAN:(Active: 3.124ms[3124094ns], % non-child: 32.63%)
               - CachedPagesNum: 0
               - CompressedBytesRead: 41.94 KB
               - CreateSegmentIter: 100.952us
               - DictDecode: 75.498us
               - IOTime: 20.402us
               - LateMaterialize: 134.64us
               - PushdownPredicates: 1
               - RawRowsRead: 21.907K (21907)
               - SegmentInit: 2.793ms
                 - BitmapIndexFilter: 0ns
                 - BitmapIndexFilterRows: 0
                 - BloomFilterFilterRows: 0
                 - ShortKeyFilterRows: 0
                 - ZoneMapIndexFilterRows: 0
               - SegmentRead: 91.115us
                 - BlockFetch: 40.277us
                 - BlockFetchCount: 7
                 - BlockSeek: 39.851us
                 - BlockSeekCount: 1
                 - ChunkCopy: 2.711us
                 - DecompressT: 6.132us
                 - DelVecFilterRows: 0
                 - IndexLoad: 0ns
                 - PredFilter: 4.41us
                 - PredFilterRows: 16.436K (16436)
               - TotalPagesNum: 8
               - UncompressedBytesRead: 42.13 KB
```
We can see that bloomfilter was not work. caused by that alter table just support add/remove column, other schema change is not supported.

**Describe the solution you'd like**
parse the schema change request in early stage, according to the result of parser, dispatch the linked and directly schema change procedure of primary key, recreate rowset, write new data into them.
