### ISSUE TITLE
Support access endpoint broker property in the 2.5 broker feature

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks#16824]
### Steps to reproduce the behavior (Required)
docker-compose.yml for setting up the minio environment
```
networks:
  docker-network:
    driver: bridge
    ipam:
      config: # network config, can change to your preferred network, e.g. subnet: 172.21.0.0/16, gateway: 172.21.0.1
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  starrocks:
    container_name: starrocks
    hostname: starrocks.local
    image: [starrock-all-in1-image]
    restart: unless-stopped
    environment:
      STARTMODE: auto # auto start a single node sr cluster with fe, be and broker setup
    ports: # port mapping format "[host port]:[container port]", can be configured to your preferred port
      - "8030:8030"
      - "8040:8040"
      - "9030:9030"
      - "8000:8000"
    networks: # network config, can be configured to your preferred port and ip address, if not specified, it will use default network and assign a dynamic ip
      docker-network:
        ipv4_address: 172.20.0.2
    #     Configure persistent volume to keep the StarRocks database state across container recreation.
    #     This way, even you have to recreate the container, e.g. updating the image from one version to another, the
    #     StarRocks database will be preserved.
    volumes: # volume mapping format "[host volume directory]:[container volume directory]", can be configured to your preferred mount point
      - ${HOME}/dockervolume/starrocks/be/storage:/data/deploy/starrocks/be/storage
      - ${HOME}/dockervolume/starrocks/be/log:/data/deploy/starrocks/be/log
      - ${HOME}/dockervolume/starrocks/fe/meta:/data/deploy/starrocks/fe/meta


  minio:
    container_name: minio
    hostname: minio.local.com
    image: quay.io/minio/minio
    restart: unless-stopped
    ports:  # port mapping format "[host port]:[container port]", can be configured to your preferred port
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ${HOME}/dockervolume/minio/data:/data
    networks: # network config, can be configured to your preferred port and ip address, if not specified, it will use default network and assign a dynamic ip
      docker-network:
        ipv4_address: 172.20.0.5
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootroot
    command: server /data --console-address ":9001"

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
