### ISSUE TITLE
[Enhancement] Have docker compose up support persistent volumes to support developer testing and development

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#19403]
## Enhancement
Right now the docker compose doesn't support persistent volumes.   If you are trying to do a lot of testing or development, having volumes that persistent from repeatable `compose down` and `compose up` is helpul. 

Here is sample modifications needed to yaml.  https://dev.to/darkmavis1980/how-to-persist-data-with-docker-compose-ik8

**Comment by ss892714028** [comment]
@alberttwong Yes, it does. Please feel free to take a look at this YAML. https://github.com/StarRocks/starrocks/blob/main/docker/docker-compose/docker-compose-3BE.yml
Remember to change `path/of/host/` to your actual directory
For FE:
```
#    volumes:
#      - path/of/host/fe.conf:/opt/starrocks/fe/conf/fe.conf
#      - path/of/host/fe/meta:/opt/starrocks/fe/meta
```
For BE:
```
#    volumes:
#      - path/of/host/be.conf:/opt/starrocks/be/conf/be.conf
#      - path/of/host/starrocks-be1/storage:/opt/starrocks/be/storage
```

**Comment by alberttwong** [comment]
Using 
```
version: "3.9"
services:
  starrocks-fe:
    image: starrocks/fe-ubuntu:main
    hostname: starrocks-fe
    container_name: starrocks-fe
    command:
      /opt/starrocks/fe/bin/start_fe.sh
    ports:
      - 8030:8030
      - 9020:9020
      - 9030:9030
    volumes:
       - fe_data:/opt/starrocks/fe/meta
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9030"]
      interval: 5s
      timeout: 5s
      retries: 30

  starrocks-be:
    image: starrocks/be-ubuntu:main
    command:
      - /bin/bash
      - -c
      - |
        sleep 15s; mysql --connect-timeout 2 -h starrocks-fe -P9030 -uroot -e "alter system add backend \"starrocks-be:9050\";"
        /opt/starrocks/be/bin/start_be.sh
    ports:
      - 8040:8040
    hostname: starrocks-be
    container_name: starrocks-be
    depends_on:
      - starrocks-fe
    volumes:
      - be1_data:/opt/starrocks/be/storage
volumes:
  fe_data:
  be1_data:

```

Scenario:
1. run `docker-compose up -d`
2. insert some data and verify
3. run `docker-compose down`
4. verify data.    won't connect.   gets error message 

`2023-03-13 12:45:05 ERROR 2003 (HY000): Can't connect to MySQL server on 'starrocks-fe:9030' (111)`

**Comment by alberttwong** [comment]
Per https://github.com/StarRocks/starrocks/blob/main/docker/docker-compose/README.md, I tried to re-compose again and  it didn't work.   Where do you run the `ADD BACKEND "<be_ip>:9050";` command?

**Comment by alberttwong** [comment]
I read the compose yaml.   You sleep 15 seconds and try again.  I can tell you that doesn't work since I waited minutes.

`mysql --connect-timeout 2 -h starrocks-fe -P9030 -uroot -e "alter system add backend \"starrocks-be:9050\";"`

**Comment by alberttwong** [comment]
Also this problem only happens when I try to start, stop and then start again.   If I delete the old volumes and start "fresh", I don't get any of these errors.

**Comment by alberttwong** [comment]
https://github.com/StarRocks/starrocks/issues/19449

**Comment by albertatcelerdata** [comment]
Answer is that FE startup script needs ;--host_type FQDN

```
version: "3.9"
services:
  starrocks-fe:
    image: starrocks/fe-ubuntu:main
    hostname: starrocks-fe
    container_name: starrocks-fe
    command:
      /opt/starrocks/fe/bin/start_fe.sh --host_type FQDN
    ports:
      - 8030:8030
      - 9020:9020
      - 9030:9030
    volumes:
       - fe_data:/opt/starrocks/fe/meta
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9030"]
      interval: 5s
      timeout: 5s
      retries: 30

  starrocks-be:
    image: starrocks/be-ubuntu:main
    command:
      - /bin/bash
      - -c
      - |
        sleep 15s; mysql --connect-timeout 2 -h starrocks-fe -P9030 -uroot -e "alter system add backend \"starrocks-be:9050\";"
        /opt/starrocks/be/bin/start_be.sh
    ports:
      - 8040:8040
    hostname: starrocks-be
    container_name: starrocks-be
    depends_on:
      - starrocks-fe
    volumes:
      - be1_data:/opt/starrocks/be/storage
volumes:
  fe_data:
  be1_data:
```
