### ISSUE TITLE
Performance issue about MV rewrite

### ISSUE THREAD

**Issue by mofeiatwork** [StarRocks/starrocks#29254]
### Steps to reproduce the behavior (Required)

1. As MV on Iceberg
2. Directly querying the MV takes only  0.01s, but if trying to leverage the query rewrite capability of MV, it takes 0.2s 
3. From the profile we can see the Query Analyzing phase take the most time

```yaml
Query:
  Summary:
     - Query ID: b9b935d8-30e9-11ee-9581-0242ac110002
     - Start Time: 2023-08-02 04:04:49
     - End Time: 2023-08-02 04:04:49
     - Total: 208ms
     - Query Type: Query
     - Query State: EOF
     - StarRocks Version: 3.0.1-a1f411b
     - User: root
     - Default Db: PUBLIC
     - Sql Statement: xxx
     - Variables: parallel_fragment_exec_instance_num=1,max_parallel_scan_instance_num=-1,pipeline_dop=0,enable_adaptive_sink_dop=true,enable_runtime_adaptive_dop=false
     - Collect 
Profile Time: 6ms
  Planner:
     - Analyzer: 203ms / 1
     - CTEUniqueChecker: 0ms / 1
     - CoordDeliverExec: 0ms / 1
     - CoordPrepareExec: 0ms / 1
     - ExecPlanBuild: 0ms / 1
     - InputDependenciesChecker: 0ms / 1
     - Optimizer: 1ms / 1
     - Total: 205ms / 1
     - Transformer: 0ms / 1
     - TypeChecker: 0ms / 1
    Optimizer:
       - CostBaseOptimize: 0ms / 1
       - PhysicalRewrite: 0ms / 1
       - PlanValidate: 0ms / 1
       - RuleBaseOptimize: 0ms / 1
       - preprocessMvs: 0ms / 1

```

### StarRocks version (Required)
-  3.0.1, 3.1.0
