### ISSUE TITLE
In k8s environment, Exchange Operator's pass through feature will not take effect 

### ISSUE THREAD

**Issue by wxl24life** [StarRocks/starrocks#29677]
In k8s environment, Exchange Operator's pass through feature will not take effect, even though `enable_exchange_pass_through` variable has already been set to true.

### Steps to reproduce the behavior (Required)

```sql
CREATE DATABASE IF NOT EXISTS load_test;
USE load_test;

CREATE TABLE insert_wiki_edit_03
(
    event_time DATETIME,
    channel VARCHAR(32) DEFAULT '',
    user VARCHAR(128) DEFAULT '',
    is_anonymous TINYINT DEFAULT '0',
    is_minor TINYINT DEFAULT '0',
    is_new TINYINT DEFAULT '0',
    is_robot TINYINT DEFAULT '0',
    is_unpatrolled TINYINT DEFAULT '0',
    delta INT SUM DEFAULT '0',
    added INT SUM DEFAULT '0',
    deleted INT SUM DEFAULT '0'
)
AGGREGATE KEY(event_time, channel, user, is_anonymous, is_minor, is_new, is_robot, is_unpatrolled)
PARTITION BY RANGE(event_time)
(
    PARTITION p06 VALUES LESS THAN ('2015-09-12 06:00:00'),
    PARTITION p12 VALUES LESS THAN ('2015-09-12 12:00:00'),
    PARTITION p18 VALUES LESS THAN ('2015-09-12 18:00:00'),
    PARTITION p24 VALUES LESS THAN ('2015-09-13 00:00:00')
)
DISTRIBUTED BY HASH(user) BUCKETS 10

PROPERTIES("replication_num" = "1");

INSERT INTO insert_wiki_edit_03 VALUES("2015-09-12 00:00:00","#en.wikipedia","GELongstreet",0,0,0,0,0,36,36,0),("2015-09-12 00:00:00","#ca.wikipedia","PereBot",0,1,0,1,0,17,17,0);

select * from insert_wiki_edit_03;
```

### Expected behavior (Required)
From query profile, we can see Exchange Operator's BytesPassThrough metrics should have some value other than 0
```
UniqueMetrics:
             - DestID: 1
             - DestFragments: 375fb6d840b211ee-902400163e125591
             - PartType: UNPARTITIONED
             - ChannelNum: 1
             - BytesPassThrough: 357.00 B
               - __MAX_OF_BytesPassThrough: 181.00 B
               - __MIN_OF_BytesPassThrough: 176.00 B
             - BytesSent: 0.00
             - CompressTime: 0ns
 ```

### Real behavior (Required)
```
UniqueMetrics:
             - DestID: 1
             - DestFragments: 375fb6d840b211ee-902400163e125591
             - PartType: UNPARTITIONED
             - ChannelNum: 1
             - BytesPassThrough: 0 B
               - __MAX_OF_BytesPassThrough: 0 B
               - __MIN_OF_BytesPassThrough: 0 B
             - BytesSent: 0.00
             - CompressTime: 0ns
 ```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
