### ISSUE TITLE
Unfinished backends in show load is incorrect

### ISSUE THREAD

**Issue by hongli-my** [StarRocks/starrocks#31444]
## Enhancement
for show load command, result is ,  Unfinished backends is relatedbackendIds for one insert query,  but  one backend will have more than one instance,  so I think this field is incorrect.
```
*************************** 26. row ***************************
         JobId: 222136
         Label: insert_5ba511c6-5762-11ee-adb8-f2810a67f2ad
         State: QUEUEING
      Progress: ETL:N/A; LOAD:N/A
          Type: INSERT
      Priority: NORMAL
       EtlInfo: NULL
      TaskInfo: resource:N/A; timeout(s):300; max_filter_ratio:0.0
      ErrorMsg: type:LOAD_RUN_FAIL; msg:Cancelled
    CreateTime: 2023-09-20 11:04:05
  EtlStartTime: 2023-09-20 11:04:05
 EtlFinishTime: 2023-09-20 11:04:05
 LoadStartTime: 2023-09-20 11:04:05
LoadFinishTime: NULL
           URL:  NULL
    JobDetails: {"All backends":{"5ba511c6-5762-11ee-adb8-f2810a67f2ad":[121062]},"FileNumber":0,"FileSize":0,"InternalTableLoadBytes":1489,"InternalTableLoadRows":37,"ScanBytes":0,"ScanRows":0,"TaskNumber":1,"Unfinished backends":{"5ba511c6-5762-11ee-adb8-f2810a67f2ad":""}}
```

I think add  counter for backend might be better  like :
```
*************************** 27. row ***************************
         JobId: 222137
         Label: insert_82df60af-5763-11ee-adb8-f2810a67f2ad
         State: QUEUEING
      Progress: ETL:N/A; LOAD:N/A
          Type: INSERT
      Priority: NORMAL
       EtlInfo: NULL
      TaskInfo: resource:N/A; timeout(s):300; max_filter_ratio:0.0
      ErrorMsg: type:LOAD_RUN_FAIL; msg:Cancelled, msg: Backend not found. Check if any backend is down or not
    CreateTime: 2023-09-20 11:12:20
  EtlStartTime: 2023-09-20 11:12:20
 EtlFinishTime: 2023-09-20 11:12:20
 LoadStartTime: 2023-09-20 11:12:20
LoadFinishTime: null
           URL:
    JobDetails: {"All backends":{"82df60af-5763-11ee-adb8-f2810a67f2ad":[121062]},"FileNumber":0,"FileSize":0,"InternalTableLoadBytes":0,"InternalTableLoadRows":0,"ScanBytes":0,"ScanRows":0,"TaskNumber":1,"Unfinished backends":{"82df60af-5763-11ee-adb8-f2810a67f2ad":"121062(2)"}}

```
