### ISSUE TITLE
[Bug] Wrong statistics of BytesUnsent

### ISSUE THREAD

**Issue by liuyehcf** [StarRocks/starrocks#31558]
```
EXCHANGE_SINK (plan_node_id=2):
          CommonMetrics:
             - CloseTime: 500ns
               - __MAX_OF_CloseTime: 7.181us
               - __MIN_OF_CloseTime: 132ns
             - OperatorAllocatedMemoryUsage: 432.148 GB
               - __MAX_OF_OperatorAllocatedMemoryUsage: 931.708 MB
               - __MIN_OF_OperatorAllocatedMemoryUsage: 907.698 MB
             - OperatorDeallocatedMemoryUsage: 269.998 GB
               - __MAX_OF_OperatorDeallocatedMemoryUsage: 693.135 MB
               - __MIN_OF_OperatorDeallocatedMemoryUsage: 451.836 MB
             - OperatorPeakMemoryUsage: 345.927 MB
               - __MAX_OF_OperatorPeakMemoryUsage: 475.806 MB
               - __MIN_OF_OperatorPeakMemoryUsage: 224.035 MB
             - OperatorTotalTime: 5s320ms
               - __MAX_OF_OperatorTotalTime: 5s947ms
               - __MIN_OF_OperatorTotalTime: 4s818ms
             - PrepareTime: 51.287us
               - __MAX_OF_PrepareTime: 94.514us
               - __MIN_OF_PrepareTime: 36.622us
             - PullChunkNum: 0
             - PullRowNum: 0
             - PullTotalTime: 0ns
             - PushChunkNum: 1.103M (1103145)
               - __MAX_OF_PushChunkNum: 2.329K (2329)
               - __MIN_OF_PushChunkNum: 2.264K (2264)
             - PushRowNum: 4.509B (4509033509)
               - __MAX_OF_PushRowNum: 9.526M (9525873)
               - __MIN_OF_PushRowNum: 9.251M (9250922)
             - PushTotalTime: 5s64ms
               - __MAX_OF_PushTotalTime: 5s635ms
               - __MIN_OF_PushTotalTime: 4s582ms
             - SetFinishedTime: 98ns
               - __MAX_OF_SetFinishedTime: 607ns
               - __MIN_OF_SetFinishedTime: 24ns
             - SetFinishingTime: 255.851ms
               - __MAX_OF_SetFinishingTime: 345.012ms
               - __MIN_OF_SetFinishingTime: 191.577ms
          UniqueMetrics:
             - ChannelNum: 20
             - DestFragments: 55f4b67f55e011ee-8acf0af38bb648ce, 55f4b67f55e011ee-8acf0af38bb648cf, 55f4b67f55e011ee-8acf0af38bb648d0, 55f4b67f55e011ee-8acf0af38bb648d1, 55f4b67f55e011ee-8acf0af38bb648d2, 55f4b67f55e011ee-8acf0af38bb648d3, 55f4b67f55e011ee-8acf0af38bb648d4, 55f4b67f55e011ee-8acf0af38bb648d5, 55f4b67f55e011ee-8acf0af38bb648d6, 55f4b67f55e011ee-8acf0af38bb648d7, 55f4b67f55e011ee-8acf0af38bb648d8, 55f4b67f55e011ee-8acf0af38bb648d9, 55f4b67f55e011ee-8acf0af38bb648da, 55f4b67f55e011ee-8acf0af38bb648db, 55f4b67f55e011ee-8acf0af38bb648dc, 55f4b67f55e011ee-8acf0af38bb648dd, 55f4b67f55e011ee-8acf0af38bb648de, 55f4b67f55e011ee-8acf0af38bb648df, 55f4b67f55e011ee-8acf0af38bb648e0, 55f4b67f55e011ee-8acf0af38bb648e1
             - DestID: 2
             - PartType: HASH_PARTITIONED
             - PipelineLevelShuffle: Yes
             - ShuffleNumPerChannel: 24
             - TotalShuffleNum: 480
             - BytesPassThrough: 9.596 GB
               - __MAX_OF_BytesPassThrough: 20.860 MB
               - __MIN_OF_BytesPassThrough: 20.041 MB
             - BytesSent: 95.711 GB
               - __MAX_OF_BytesSent: 4.835 GB
               - __MIN_OF_BytesSent: 4.726 GB
             - BytesUnsent: 4.951 GB
               - __MAX_OF_BytesUnsent: 578.287 MB
               - __MIN_OF_BytesUnsent: 1020.541 KB
             - CompressTime: 0ns
             - NetworkBandwidth: 2.302 TB/sec
               - __MAX_OF_NetworkBandwidth: 243.591 GB/sec
               - __MIN_OF_NetworkBandwidth: 7.840 GB/sec
             - NetworkTime: 184.794ms
               - __MAX_OF_NetworkTime: 607.521ms
               - __MIN_OF_NetworkTime: 19.756ms
             - OverallThroughput: 3.882 GB/sec
               - __MAX_OF_OverallThroughput: 204.659 MB/sec
               - __MIN_OF_OverallThroughput: 190.966 MB/sec
             - OverallTime: 24s664ms
               - __MAX_OF_OverallTime: 25s596ms
               - __MIN_OF_OverallTime: 24s142ms
             - RequestSent: 350.030K (350030)
               - __MAX_OF_RequestSent: 17.681K (17681)
               - __MIN_OF_RequestSent: 17.357K (17357)
             - RequestUnsent: 18.216K (18216)
               - __MAX_OF_RequestUnsent: 2.086K (2086)
               - __MIN_OF_RequestUnsent: 11
             - RpcAvgTime: 976.151us
               - __MAX_OF_RpcAvgTime: 1.427ms
               - __MIN_OF_RpcAvgTime: 794.308us
             - RpcCount: 378.549K (378549)
               - __MAX_OF_RpcCount: 19.128K (19128)
               - __MIN_OF_RpcCount: 18.757K (18757)
             - SerializeChunkTime: 1s298ms
               - __MAX_OF_SerializeChunkTime: 1s557ms
               - __MIN_OF_SerializeChunkTime: 1s194ms
             - ShuffleHashTime: 339.115ms
               - __MAX_OF_ShuffleHashTime: 468.048ms
               - __MIN_OF_ShuffleHashTime: 268.847ms
             - UncompressedBytes: 95.711 GB
               - __MAX_OF_UncompressedBytes: 207.317 MB
               - __MIN_OF_UncompressedBytes: 200.857 MB
             - WaitTime: 19s783ms
               - __MAX_OF_WaitTime: 20s798ms
               - __MIN_OF_WaitTime: 18s881ms
```

```
EXCHANGE_SOURCE (plan_node_id=2):
          CommonMetrics:
             - CloseTime: 799ns
               - __MAX_OF_CloseTime: 3.166us
               - __MIN_OF_CloseTime: 239ns
             - JoinRuntimeFilterEvaluate: 0
             - JoinRuntimeFilterHashTime: 0ns
             - JoinRuntimeFilterInputRows: 0
             - JoinRuntimeFilterOutputRows: 0
             - JoinRuntimeFilterTime: 0ns
             - OperatorAllocatedMemoryUsage: 271.038 GB
               - __MAX_OF_OperatorAllocatedMemoryUsage: 646.475 MB
               - __MIN_OF_OperatorAllocatedMemoryUsage: 545.365 MB
             - OperatorDeallocatedMemoryUsage: 284.233 GB
               - __MAX_OF_OperatorDeallocatedMemoryUsage: 894.644 MB
               - __MIN_OF_OperatorDeallocatedMemoryUsage: 425.764 MB
             - OperatorPeakMemoryUsage: 7.348 MB
               - __MAX_OF_OperatorPeakMemoryUsage: 214.418 MB
               - __MIN_OF_OperatorPeakMemoryUsage: 0.000 B
             - OperatorTotalTime: 309.433ms
               - __MAX_OF_OperatorTotalTime: 382.553ms
               - __MIN_OF_OperatorTotalTime: 274.698ms
             - PrepareTime: 21.378us
               - __MAX_OF_PrepareTime: 394.949us
               - __MIN_OF_PrepareTime: 4.398us
             - PullChunkNum: 1.160M (1160022)
               - __MAX_OF_PullChunkNum: 2.880K (2880)
               - __MIN_OF_PullChunkNum: 2.400K (2400)
             - PullRowNum: 4.509B (4509033509)
               - __MAX_OF_PullRowNum: 10.412M (10411761)
               - __MIN_OF_PullRowNum: 8.875M (8874952)
             - PullTotalTime: 309.423ms
               - __MAX_OF_PullTotalTime: 382.547ms
               - __MIN_OF_PullTotalTime: 274.692ms
             - PushChunkNum: 0
             - PushRowNum: 0
             - PushTotalTime: 0ns
             - RuntimeBloomFilterNum: 0
             - RuntimeInFilterNum: 0
             - SetFinishedTime: 138ns
               - __MAX_OF_SetFinishedTime: 481ns
               - __MIN_OF_SetFinishedTime: 26ns
             - SetFinishingTime: 8.473us
               - __MAX_OF_SetFinishingTime: 91.275us
               - __MIN_OF_SetFinishingTime: 676ns
          UniqueMetrics:
             - BufferUnplugCount: 1.155K (1155)
               - __MAX_OF_BufferUnplugCount: 111
               - __MIN_OF_BufferUnplugCount: 31
             - BytesPassThrough: 9.596 GB
               - __MAX_OF_BytesPassThrough: 498.201 MB
               - __MIN_OF_BytesPassThrough: 483.410 MB
             - BytesReceived: 95.711 GB
               - __MAX_OF_BytesReceived: 4.815 GB
               - __MIN_OF_BytesReceived: 4.741 GB
             - ClosureBlockCount: 359.818K (359818)
               - __MAX_OF_ClosureBlockCount: 18.419K (18419)
               - __MIN_OF_ClosureBlockCount: 17.231K (17231)
             - ClosureBlockTime: 4h35m
               - __MAX_OF_ClosureBlockTime: 5h44m
               - __MIN_OF_ClosureBlockTime: 2h50m
             - DecompressChunkTime: 0ns
             - DeserializeChunkTime: 6s152ms
               - __MAX_OF_DeserializeChunkTime: 6s289ms
               - __MIN_OF_DeserializeChunkTime: 5s914ms
             - PeakBufferMemoryBytes: 6.438 GB
               - __MAX_OF_PeakBufferMemoryBytes: 390.208 MB
               - __MIN_OF_PeakBufferMemoryBytes: 250.404 MB
             - ReceiverProcessTotalTime: 1s405ms
               - __MAX_OF_ReceiverProcessTotalTime: 1s484ms
               - __MIN_OF_ReceiverProcessTotalTime: 1s307ms
             - RequestReceived: 378.341K (378341)
               - __MAX_OF_RequestReceived: 19.178K (19178)
               - __MIN_OF_RequestReceived: 18.754K (18754)
             - SenderTotalTime: 1s402ms
               - __MAX_OF_SenderTotalTime: 1s480ms
               - __MIN_OF_SenderTotalTime: 1s304ms
             - SenderWaitLockTime: 110ns
               - __MAX_OF_SenderWaitLockTime: 192ns
               - __MIN_OF_SenderWaitLockTime: 65ns
```

### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
