### ISSUE TITLE
To load parquet file has been fail.

### ISSUE THREAD

**Issue by kakao-lunarvel-vet** [StarRocks/starrocks#32467]
We've tried to load parquet file from s3 api.
(A table with 8,000 columns has roughly 5,000 rows.)

Few hour later, some starrocks BE nodes have killed by self.

But memory and storage space was enough to insert records.

### Steps to reproduce the behavior (Required)

1. CREATE TABLE '...'
column#: 8,000 (2000 integer, 6000 decimal)
```
CREATE TABLE tbl_pk_dec_c8000_r200000
(
    int_col1 INT,
    int_col2 INT,
    int_col3 INT,
    int_col4 INT,
    int_col5 INT,
...
    dec_col5999 DECIMAL(17,7),
    dec_col6000 DECIMAL(17,7)
)
PRIMARY KEY(int_col1)
DISTRIBUTED BY HASH(int_col1) BUCKETS 20
PROPERTIES("replication_num" = "3");
```

2. INSERT INTO '....'
```
LOAD LABEL tbl_pk_dec_c8000_r200000
(
    DATA INFILE("s3a://test/dec_c8000_r200000.001.parquet")
    INTO TABLE tbl_pk_dec_c8000_r200000
    -- COLUMNS TERMINATED BY ","
    FORMAT AS "PARQUET"
    (
    int_col1,
    int_col2,
    int_col3,
...
    dec_col5998,
    dec_col5999,
    dec_col6000
    )
)
WITH BROKER
(
    "aws.s3.endpoint" = "<storage_addr>",
    "aws.s3.access_key" = "....",
    "aws.s3.secret_key" = "....",
    "aws.s3.enable_ssl" = "true",
    "aws.s3.enable_path_style_access" = "true"
);
```

- dec_c8000_r200000.001.parquet
  - size: 1.1G
  - rows: 5,115

### Expected behavior (Required)
complete to load

#### memory status (top)
<img width="892" alt="image" src="https://github.com/StarRocks/starrocks/assets/130424337/b4f4e386-b62b-4d33-8b1f-6fd58089e27e">

#### show load\G
```
*************************** 2. row ***************************
         JobId: 14005
         Label: tbl_pk_dec_c8000_r200000
         State: CANCELLED
      Progress: ETL:N/A; LOAD:N/A
          Type: BROKER
      Priority: NORMAL
      ScanRows: 835
  FilteredRows: 0
UnselectedRows: 0
      SinkRows: 835
       EtlInfo: NULL
      TaskInfo: resource:N/A; timeout(s):14400; max_filter_ratio:0.0
      ErrorMsg: type:LOAD_RUN_FAIL; msg:[E1014]Got EOF of Socket{id=116 fd=190 addr=10.202.14.125:8060:50134} (0x0x7ffab6563740) [R1][E112]Not connected to 10.202.14.125:8060 yet, server_id=116 [R2][E112]Not connected to 10.202.14.125:8060 yet, server_id=116 [R3][E112]Not connected to 10.202.14.125:8060 yet, server_id=116
    CreateTime: 2023-09-25 14:13:17
  EtlStartTime: 2023-09-25 14:13:23
 EtlFinishTime: 2023-09-25 14:13:23
 LoadStartTime: 2023-09-25 14:13:23
LoadFinishTime: 2023-09-25 14:56:48
   TrackingSQL:
    JobDetails: {"All backends":{"d2f70bc9-a641-442d-a997-9bb0f71cade0":[10009,10007,10006,10008]},"FileNumber":1,"FileSize":1155971344,"InternalTableLoadBytes":53505686,"InternalTableLoadRows":835,"ScanBytes":53441670,"ScanRows":835,"TaskNumber":1,"Unfinished backends":{"d2f70bc9-a641-442d-a997-9bb0f71cade0":[10009,10007,10006]}}

```

#### be2: be.WARNING
```
W0925 14:56:44.756848 404252 stack_util.cpp:350] 2023-09-25 14:56:44.756733, query_id=00000000-0000-0000-0000-000000000000, fragment_instance_id=00000000-0000-0000-0000-000000000000 throws exception: std::bad_alloc, trace:
     @          0xbd4c46d  __wrap___cxa_throw
    @          0x863f966  _Znwm.cold
    @          0x86d9a4c  std::__new_allocator<>::allocate()
    @          0x86d6aff  std::allocator_traits<>::allocate()
    @          0x8743d0c  std::_Vector_base<>::_M_allocate()
    @          0x8743bab  std::_Vector_base<>::_M_create_storage()
    @          0x874195b  std::_Vector_base<>::_Vector_base()
    @          0x8831a4d  std::vector<>::vector()
    @          0x88102a3  starrocks::FixedLengthColumnBase<>::FixedLengthColumnBase()
    @          0x8bb4919  starrocks::ColumnFactory<>::ColumnFactory<>()
    @          0x8bb46f1  starrocks::FixedLengthColumn<>::FixedLengthColumn()
    @          0xc48a5cb  std::_Construct<>()
    @          0xc489d90  std::allocator_traits<>::construct<>()
    @          0xc48912b  std::_Sp_counted_ptr_inplace<>::_Sp_counted_ptr_inplace<>()
    @          0xc487ba4  std::__shared_count<>::__shared_count<>()
    @          0xc486930  std::__shared_ptr<>::__shared_ptr<>()
    @          0xc485d67  std::shared_ptr<>::shared_ptr<>()
    @          0xc485502  std::make_shared<>()
    @          0xc484e1a  starrocks::ColumnFactory<>::create<>()
    @          0xc48418b  starrocks::ColumnBuilder::operator()<>()
    @          0xc4834f3  _ZN9starrocks20type_dispatch_columnINS_13ColumnBuilderEJNS_14TypeDescriptorEmEEEDaNS_11LogicalTypeET_DpT0_
    @          0xc481a51  starrocks::ColumnHelper::create_column()
    @          0xca1caf9  starrocks::serde::ProtobufChunkDeserializer::deserialize()
    @          0xbb3a082  starrocks::LoadChannel::_deserialize_chunk()
    @          0xbb38d2f  starrocks::LoadChannel::add_chunk()
    @          0xbb31f04  starrocks::LoadChannelMgr::add_chunk()
    @          0xbc6049b  starrocks::BackendInternalServiceImpl<>::tablet_writer_add_chunk()
    @          0xc1df97a  doris::PBackendService::CallMethod()
    @          0xd44f1a1  brpc::policy::ProcessRpcRequest()
    @          0xd533707  brpc::ProcessInputMessage()
    @          0xd5345a7  brpc::InputMessenger::OnNewMessages()
    @          0xd3dac1d  brpc::Socket::ProcessEvent()
 ```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
3.1.2-4f3a2ee91b
```
