### ISSUE TITLE
Broker load extract column from path failure

### ISSUE THREAD

**Issue by rickif** [StarRocks/starrocks#32721]
### Steps to reproduce the behavior (Required)
1. Load a file by broker load with columns from path `hdfs://127.0.0.1:9000/column-from-path/year=2023/month=10/a/b.parquet`
```
 LOAD LABEL db0.laaaaaab1el2 (     DATA INFILE("hdfs://127.0.0.1:9000/column-from-path/year=2023/a/b.parquet")     INTO TABLE tbl_student_year_month     FORMAT AS "parquet"     (name, age)         COLUMNS FROM PATH AS (year)  ) WITH BROKER;

```

### Expected behavior (Required)
The load is successful.
### Real behavior (Required)
The load reports error.
```
*************************** 13. row ***************************
         JobId: 13028
         Label: ladfaaaaab1el2
         State: CANCELLED
      Progress: ETL:N/A; LOAD:N/A
          Type: BROKER
      Priority: NORMAL
      ScanRows: 0
  FilteredRows: 0
UnselectedRows: 0
      SinkRows: 0
       EtlInfo: NULL
      TaskInfo: resource:N/A; timeout(s):14400; max_filter_ratio:0.0
      ErrorMsg: type:ETL_RUN_FAIL; msg:Fail to parse columnsFromPath, expected: year, filePath: hdfs://127.0.0.1:9000/column-from-path/year=2023/a/b.parquet
    CreateTime: 2023-10-13 15:40:05
  EtlStartTime: NULL
 EtlFinishTime: NULL
 LoadStartTime: NULL
LoadFinishTime: 2023-10-13 15:40:07
   TrackingSQL: 
    JobDetails: {"All backends":{},"FileNumber":1,"FileSize":1261,"InternalTableLoadBytes":0,"InternalTableLoadRows":0,"ScanBytes":0,"ScanRows":0,"TaskNumber":0,"Unfinished backends":{}}

```
### StarRocks version (Required)
3.2, 3.1,3.0,2.5
