### ISSUE TITLE
Backend node not found. Check if any backend node is down.

### ISSUE THREAD

**Issue by techkuz** [StarRocks/starrocks#34070]
Ok, guys, really need some help over here. I am trying to make a PoC using starrocks and deploy via k8s.

At the end stages I keep getting:

```
mysql> select 1;
ERROR 1064 (HY000): Backend node not found. Check if any backend node is down.
```

### Steps to reproduce the behavior (Required)

I am using a bit edited code from here https://github.com/StarRocks/starrocks-kubernetes-operator/blob/main/examples/starrocks/deploy_a_starrocks_cluster_running_in_share_data_mode.yaml (added some info about AWS connection)

As a result, I have 

a-starrocks-in-share-data-mode-cn-0   0/1     Pending   0          13m
a-starrocks-in-share-data-mode-fe-0   1/1     Running   0          14m
a-starrocks-in-share-data-mode-fe-1   1/1     Running   0          14m
a-starrocks-in-share-data-mode-fe-2   1/1     Running   0          14m

and an operator

```

# This manifest deploys a StarRocks cluster running in shared data mode.
# see https://docs.starrocks.io/en-us/latest/deployment/deploy_shared_data for more information about share data mode.
#
# You will have to download and edit this YAML file to specify the details for your shared storage. See the 
# examples in the docs, and add your customizations to the ConfigMap `starrockscluster-sample-fe-cm` at the 
# bottom of this file.
# https://docs.starrocks.io/en-us/latest/deployment/deploy_shared_data#configure-fe-nodes-for-shared-data-starrocks

apiVersion: starrocks.com/v1
kind: StarRocksCluster
metadata:
  name: a-starrocks-in-share-data-mode   # change the name if needed.
spec:
  starRocksFeSpec:
    image: starrocks/fe-ubuntu:latest
    replicas: 3
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 8
      memory: 16Gi
    configMapInfo:
      configMapName: starrockscluster-sample-fe-cm
      resolveKey: fe.conf
  starRocksCnSpec:
    image: starrocks/cn-ubuntu:latest
    replicas: 1
    limits:
      cpu: 16
      memory: 64Gi
    requests:
      cpu: 16
      memory: 64Gi

---

# fe config
apiVersion: v1
kind: ConfigMap
metadata:
  name: starrockscluster-sample-fe-cm
  labels:
    cluster: starrockscluster-sample
data:
  fe.conf: |
    LOG_DIR = ${STARROCKS_HOME}/log
    DATE = "$(date +%Y%m%d-%H%M%S)"
    JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:${LOG_DIR}/fe.gc.log.$DATE"
    JAVA_OPTS_FOR_JDK_9="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xlog:gc*:${LOG_DIR}/fe.gc.log.$DATE:time"
    JAVA_OPTS_FOR_JDK_11="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:+UseG1GC -Xlog:gc*:${LOG_DIR}/fe.gc.log.$DATE:time"
    http_port = 8030
    rpc_port = 9020
    query_port = 9030
    edit_log_port = 9010
    mysql_service_nio_enabled = true
    sys_log_level = INFO
    # config for share data mode
    run_mode = shared_data
    cloud_native_meta_port = 6090
    cloud_native_storage_type = S3

    # For example, testbucket/subpath
    aws_s3_path = 

    # For example, us-west-2
    aws_s3_region = 

    # For example, https://s3.us-west-2.amazonaws.com
    aws_s3_endpoint =

    # credentials for S3 object read/write
    aws_s3_access_key = 
    aws_s3_secret_key = 
```
    

### Expected behavior (Required)
I can use shared-data starrocks
### Real behavior (Required)
I keep getting no backend error
### StarRocks version (Required)
3.1.3-384ba23554
