### ISSUE TITLE
社区版3.2.1存算分离docker 不可持久化

### ISSUE THREAD

**Issue by hellomyheart** [StarRocks/starrocks#42786]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

fe部分
我按照最新的教程修改了docker compose的配置

```yaml
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/fe/bin/start_fe.sh
    volumes:
      - ./data/fe:/opt/starrocks/fe/conf
    ```

/opt/starrocks/fe/conf/fe.conf 里面的配置文件被我挂载在本地，
使用阿里云OSS作为外部存储， 使用存算分离， 具体配置如下：

```conf
# enable shared data, set storage type, set endpoint
run_mode = shared_data
cloud_native_meta_port = 6090
cloud_native_storage_type = S3
aws_s3_path = xxx/xx1
aws_s3_region = oss-cn-hangzhou
aws_s3_endpoint = https://oss-cn-hangzhou.aliyuncs.com
aws_s3_access_key = xxxx
aws_s3_secret_key = xxxx
enable_load_volume_from_conf = true
```
正常启动，但是每当我重新启动docker 实例时， 我的oss都会在 xxx/xxx1下再创建一个文件夹， 导致每次重新启动都是新的实例数据

![image](https://github.com/StarRocks/starrocks/assets/31239692/6162ab44-aea0-4f63-b13c-231a6cc2ca36)

我要如何配置才能持久化启动？ 
我初步怀疑是存储卷， 需要挂载一个整体的存储卷，但是没有文档，我不知道要如何挂载

**Comment by kevincai** [comment]
fe is not in compute-storage arch yet, you have to persistent `fe/meta` somehow, either to host volumeMount or remote posix fs.

**Comment by hellomyheart** [comment]
> fe is not in compute-storage arch yet, you have to persistent `fe/meta` somehow, either to host volumeMount or remote posix fs.

How do I configure volumes in docker-compose? Are there any other configurations needed?

**Comment by kevincai** [comment]
https://docs.docker.com/compose/compose-file/07-volumes/

here is also an example for it https://github.com/StarRocks/demo/blob/master/deploy/starrocks-stack-compose/docker-compose.yml

**Comment by hellomyheart** [comment]
> https://docs.docker.com/compose/compose-file/07-volumes/
> 
> here is also an example for it https://github.com/StarRocks/demo/blob/master/deploy/starrocks-stack-compose/docker-compose.yml
I followed the example you provided, modified my docker-compose file, waited a few minutes, then ran docker compose stop, followed by docker compose up. The persistence issue with fe should be resolved as there are no new folders in oss, but there is an error in the logs.

```log
starrocks-fe  | JAVA_OPTS_FOR_JDK_11 is not set in fe.conf, use default java options for jdk11 to start fe process: -Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:+UseG1GC -Xlog:gc*:/opt/starrocks/fe/log/fe.gc.log.20240321-013014:time
starrocks-cn  | ERROR 1064 (HY000) at line 1: Unexpected exception: Compute node already exists with same host 172.30.0.3 and port 9050
starrocks-cn  | Backend running as process 1. Stop it first.
starrocks-cn exited with code 0
```

The second log message states that port 9050 and IP 172.30.0.3 are in use, but upon checking, they are actually not occupied. Below is my docker-compose file, and I have already configured fe.conf locally.

```yaml
version: "3"

services:
# fe
  starrocks-fe:
    image: starrocks/fe-ubuntu:3.2-latest
    hostname: starrocks-fe
    container_name: starrocks-fe
    user: root
    command:
      - /bin/bash
      - -c
      - |

        /opt/starrocks/fe/bin/start_fe.sh
    volumes:
      - ./data/fe/conf:/opt/starrocks/fe/conf
      - ./data/fe/meta:/opt/starrocks/fe/meta
      - ./data/fe/log:/opt/starrocks/fe/log
    ports:
      - 8030:8030
      - 9020:9020
      - 9030:9030
    healthcheck:
      test: 'mysql -u root -h starrocks-fe -P 9030 -e "show frontends\G" |grep "Alive: true"'
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
# cn
  starrocks-cn:
    image: starrocks/cn-ubuntu:3.2-latest
    command:
      - /bin/bash
      - -c
      - |
        sleep 15s;
        ulimit -u 65535;
        ulimit -n 65535;

        mysql --connect-timeout 2 -h starrocks-fe -P9030 -uroot -e "ALTER SYSTEM ADD COMPUTE NODE \"starrocks-cn:9050\";"
        /opt/starrocks/cn/bin/start_cn.sh
    ports:
      - 8040:8040
    volumes:
      #- ./data/cn/conf:/opt/starrocks/cn/conf
      - ./data/cn/storage:/opt/starrocks/cn/storage
      - ./data/cn/log:/opt/starrocks/cn/log
    hostname: starrocks-cn
    container_name: starrocks-cn
    user: root
    depends_on:
      - starrocks-fe
    healthcheck:
      test: 'mysql -u root -h starrocks-fe -P 9030 -e "SHOW COMPUTE NODES\G" |grep "Alive: true"'
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
```

Is this a new issue? Will it be resolved later?

**Comment by yandongxiao** [comment]
‌‌‌This is because the MySQL command you executed below failed.
```
# I executed the following command on fe.
root@starrocks-fe:/opt/starrocks/fe/conf# mysql --connect-timeout 2 -h 127.0.0.1 -P9030 -uroot -e "ALTER SYSTEM ADD COMPUTE NODE \"starrocks-cn:9050\";"

ERROR 1064 (HY000) at line 1: Unexpected exception: Compute node already exists with same host 172.23.0.3 and port 9050
```

Because you have already added the CN node during the first startup, repeating `ALTER SYSTEM ADD COMPUTE NODE` will result in the error mentioned above.

**Comment by yandongxiao** [comment]
I think you are using a wrong script as entrypoint. please use this:

```
version: "3"
services:
  starrocks-fe-0:
    image: starrocks/fe-ubuntu:3.2.2
    hostname: starrocks-fe-0
    container_name: starrocks-fe-0
    command:
      - /bin/bash
      - -c
      - |
        #/opt/starrocks/fe_entrypoint.sh starrocks-fe-0
        sleep 10000
    environment:
      - HOST_TYPE=FQDN
      - TZ=Asia/Shanghai
    ports:
      - "8030:8030"
      - "9030:9030"
    volumes:
      - ./data/fe/meta:/opt/starrocks/fe/meta
      - ./data/fe/log:/opt/starrocks/fe/log
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8030/api/health"]
      interval: 5s
      timeout: 5s
      retries: 30

  starrocks-cn-0:
    image: starrocks/cn-ubuntu:3.2.2
    hostname: starrocks-cn-0
    container_name: starrocks-cn-0
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/cn_entrypoint.sh starrocks-fe-0
    environment:
      - HOST_TYPE=FQDN
      - TZ=Asia/Shanghai
    ports:
      - "8040:8040"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8040/api/health"]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - ./data/cn/storage:/opt/starrocks/cn/storage
      - ./data/cn/log:/opt/starrocks/cn/log
    depends_on:
      - starrocks-fe-0
```

**Comment by hellomyheart** [comment]
> I think you are using a wrong script as entrypoint. please use this:
> 
> ```
> version: "3"
> services:
>   starrocks-fe-0:
>     image: starrocks/fe-ubuntu:3.2.2
>     hostname: starrocks-fe-0
>     container_name: starrocks-fe-0
>     command:
>       - /bin/bash
>       - -c
>       - |
>         #/opt/starrocks/fe_entrypoint.sh starrocks-fe-0
>         sleep 10000
>     environment:
>       - HOST_TYPE=FQDN
>       - TZ=Asia/Shanghai
>     ports:
>       - "8030:8030"
>       - "9030:9030"
>     volumes:
>       - ./data/fe/meta:/opt/starrocks/fe/meta
>       - ./data/fe/log:/opt/starrocks/fe/log
>     healthcheck:
>       test: ["CMD", "curl", "-f", "http://localhost:8030/api/health"]
>       interval: 5s
>       timeout: 5s
>       retries: 30
> 
>   starrocks-cn-0:
>     image: starrocks/cn-ubuntu:3.2.2
>     hostname: starrocks-cn-0
>     container_name: starrocks-cn-0
>     command:
>       - /bin/bash
>       - -c
>       - |
>         /opt/starrocks/cn_entrypoint.sh starrocks-fe-0
>     environment:
>       - HOST_TYPE=FQDN
>       - TZ=Asia/Shanghai
>     ports:
>       - "8040:8040"
>     healthcheck:
>       test: ["CMD", "curl", "-f", "http://localhost:8040/api/health"]
>       interval: 5s
>       timeout: 5s
>       retries: 30
>     volumes:
>       - ./data/cn/storage:/opt/starrocks/cn/storage
>       - ./data/cn/log:/opt/starrocks/cn/log
>     depends_on:
>       - starrocks-fe-0
> ```

I used the docker-compose.yml file above, but the services failed to start. I made changes to my docker-compose.yml file. After running the 'docker compose stop' command, I commented out the line 'mysql --connect-timeout 2 -h starrocks-fe -P9030 -uroot -e "ALTER SYSTEM ADD COMPUTE NODE "starrocks-cn:9050";". After that, when I started 'docker compose up', everything ran smoothly. Can I continue using this approach? If the images are updated, will this approach still work?

Below is my modified docker-compose configuration file."

```yaml
version: "3"

services:
# fe
  starrocks-fe:
    image: starrocks/fe-ubuntu:3.2-latest
    hostname: starrocks-fe
    container_name: starrocks-fe
    user: root
    command:
      - /bin/bash
      - -c
      - |

        /opt/starrocks/fe/bin/start_fe.sh
    volumes:
      - ./data/fe/conf:/opt/starrocks/fe/conf
      - ./data/fe/meta:/opt/starrocks/fe/meta
      - ./data/fe/log:/opt/starrocks/fe/log
    ports:
      - 8030:8030
      - 9020:9020
      - 9030:9030
    healthcheck:
      test: 'mysql -u root -h starrocks-fe -P 9030 -e "show frontends\G" |grep "Alive: true"'
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
# cn
  starrocks-cn:
    image: starrocks/cn-ubuntu:3.2-latest
    command:
      - /bin/bash
      - -c
      - |
        sleep 15s;
        ulimit -u 65535;
        ulimit -n 65535;

        #mysql --connect-timeout 2 -h starrocks-fe -P9030 -uroot -e "ALTER SYSTEM ADD COMPUTE NODE \"starrocks-cn:9050\";"
        /opt/starrocks/cn/bin/start_cn.sh
    ports:
      - 8040:8040
    volumes:
      #- ./data/cn/conf:/opt/starrocks/cn/conf
      - ./data/cn/storage:/opt/starrocks/cn/storage
      - ./data/cn/log:/opt/starrocks/cn/log
    hostname: starrocks-cn
    container_name: starrocks-cn
    user: root
    depends_on:
      - starrocks-fe
    healthcheck:
      test: 'mysql -u root -h starrocks-fe -P 9030 -e "SHOW COMPUTE NODES\G" |grep "Alive: true"'
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
```
