### ISSUE TITLE
[Flat Json] Incorrect detail field in profile

### ISSUE THREAD

**Issue by wangruin** [StarRocks/starrocks#43782]
### Steps to reproduce the behavior (Required)
`select get_json_string(k2,'\$.Integer') from t1 where k2->'str' = 'test_flat_json';`
```
          UniqueMetrics:
             - MorselQueueType: fixed_morsel_queue
             - Predicates: json_query(2: k2, 'str') = CAST('test_flat_json' AS JSON)
             - Rollup: t1
             - SharedScan: False
             - Table: t1
             - AccessPathHits: 6
               - __MAX_OF_AccessPathHits: 3
               - __MIN_OF_AccessPathHits: 1
               - /k2: 7
                 - __MAX_OF_/k2: 3
                 - __MIN_OF_/k2: 2
             - AccessPathUnhits: 1
               - __MAX_OF_AccessPathUnhits: 1
               - __MIN_OF_AccessPathUnhits: 0
```

`select k1,get_json_string(k2,'\$.Integer') from t1 where k2->'str' = 'test_flat_json';`
```
          UniqueMetrics:
             - MorselQueueType: fixed_morsel_queue
             - Predicates: json_query(2: k2, 'str') = CAST('test_flat_json' AS JSON)
             - Rollup: t1
             - SharedScan: False
             - Table: t1
             - AccessPathHits: 2
               - __MAX_OF_AccessPathHits: 1
               - __MIN_OF_AccessPathHits: 0
             - AccessPathUnhits: 1
               - __MAX_OF_AccessPathUnhits: 1
               - __MIN_OF_AccessPathUnhits: 0
               - /k2: 3
                 - __MAX_OF_/k2: 1
                 - __MIN_OF_/k2: 1
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main-f6aaa7b
