### ISSUE TITLE
Add more refresh info into profile/audit log for performace analysis for materialized view refresh

### ISSUE THREAD

**Issue by LiShuMing** [StarRocks/starrocks#46953]
## Enhancement

Here is a profile for mv refresh, the total time is `2min33s`, however we cannot distinguish which phases is the most time cost.

```
  Summary:
     - Query ID: 3bebb5f4-27bd-11ef-8972-0242bb531d62
     - Start Time: 2024-06-11 14:38:38
     - End Time: 2024-06-11 14:41:11
     - Total: 2m33s
     - Query Type: Query
     - Query State: Finished
Planner:
     - Analyzer: 1ms / 1
     - CTEUniqueChecker: 0ms / 2
     - ColumnReuseChecker: 0ms / 2
     - InputDependenciesChecker: 0ms / 2
     - InsertPlanner: 710ms / 2
     - Optimizer: 706ms / 2
     - PlanBuilder: 3ms / 2
     - Transform: 4ms / 2
     - TypeChecker: 0ms / 2
  
    Optimizer:
       - CostBaseOptimize: 692ms / 2
       - PhysicalRewrite: 0ms / 2
       - PlanValidate: 0ms / 2
       - RuleBaseOptimize: 12ms / 2
       - preprocessMvs: 0ms / 2
      preprocessMvs:
         - chooseCandidates: 0ms / 2
         - generateMvPlan: 0ms / 2
         - validateMv: 0ms / 2
    RuleBaseOptimize:
      RewriteTreeTask:
         - ExternalTablePartitionPrune: 0ms / 10
    Scheduler:
       - Deploy: 43ms / 1
       - Pending: 0ms / 1
       - Prepare: 2ms / 1
    Iceberg:
      Metadata:
        ScanMetrics:

  Execution:

     - FrontendProfileMergeTime: 50.626ms
     - QueryAllocatedMemoryUsage: 62.577 GB
     - QueryCumulativeCpuTime: 13s797ms
     - QueryCumulativeNetworkTime: 13.346ms
     - QueryCumulativeOperatorTime: 4s431ms
     - QueryCumulativeScanTime: 746.786ms
     - QueryDeallocatedMemoryUsage: 62.183 GB
     - QueryExecutionWallTime: 10s110ms
     - QueryPeakMemoryUsage: 298.370 MB
     - QueryPeakScheduleTime: 360.753ms
     - QuerySpillBytes: 0.000 B
     - ResultDeliverTime: 3s956ms

```

This is  because `PartitionBasedMvRefreshProcessor` may cost a lot of time before real query execution(syncPartition/analyze/try lock...), we should take care those phases into profile for better analysis.
