### ISSUE TITLE
Lose profile in pipeline mode

### ISSUE THREAD

**Issue by mofeiatwork** [StarRocks/starrocks#4883]
### Steps to reproduce the behavior (Required)
testcase: test_create_bitmap_index.TestCreateBitmapIndex.test_bitmap_index_for_char

query:
```sql
SELECT SUM(k7), SUM(k8), MAX(k9), MAX(k10)                  
FROM duplicate_table_with_null                  
WHERE k3 = 'guangzhou'
```

### Expected behavior (Required)
Utilize bitmap index to skip data.

### Real behavior (Required)
Profile loss, which appears not using bitmap index, but actually it indeed apply the bitmap index.

non-pipeline mode:
```yaml
              SCAN:(Active: 485.85us[485085ns], % non-child: 0.01%)
                 - CachedPagesNum: 0
                 - CompressedBytesRead: 42.25 KB
                 - CreateSegmentIter: 42.990us
                 - DictDecode: 891ns
                 - IOTime: 23.492us
                 - LateMaterialize: 227.220us
                 - PushdownPredicates: 1
                 - RawRowsRead: 5.522K (5522)
                 - ReadPagesNum: 7
                 - SegmentInit: 127.724us
                   - BitmapIndexFilter: 37.277us
                   - BitmapIndexFilterRows: 16.51K (16510)
                   - BloomFilterFilterRows: 0
                   - SegmentZoneMapFilterRows: 0
                   - ShortKeyFilterRows: 0
                   - ZoneMapIndexFilterRows: 0
                 - SegmentRead: 63.521us
                   - BlockFetch: 30.22us
                   - BlockFetchCount: 2
                   - BlockSeek: 30.485us
                   - BlockSeekCount: 2
                   - ChunkCopy: 0ns
                   - DecompressT: 13.377us
                   - DelVecFilterRows: 0
                   - IndexLoad: 0ns
                   - PredFilter: 0ns
                   - PredFilterRows: 0
                   - RowsetsReadCount: 2
                   - SegmentsReadCount: 1
                   - TotalColumnsDataPageCount: 14
                 - UncompressedBytesRead: 42.18 KB
```

pipeline mode:
```yaml
             - ScanTime: 8s849ms
               - __MAX_OF_ScanTime: 26s546ms
               - __MIN_OF_ScanTime: 922.232us
             - SegmentInit: 0ns
               - BitmapIndexFilter: 0ns
               - BitmapIndexFilterRows: 0
               - BloomFilterFilterRows: 0
               - ShortKeyFilterRows: 0
               - ZoneMapIndexFilterRows: 0
             - SegmentRead: 0ns
               - BlockFetch: 0ns
               - BlockFetchCount: 0
               - BlockSeek: 0ns
               - BlockSeekCount: 0
               - ChunkCopy: 0ns
               - DecompressT: 0ns
               - DelVecFilterRows: 0
               - IndexLoad: 0ns
               - PredFilter: 0ns
               - PredFilterRows: 0
               - RowsetsReadCount: 0
               - SegmentsReadCount: 0
               - TotalColumnsDataPageCount: 0
             - UncompressedBytesRead: 0.00 

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - commit `a561464`
