### ISSUE TITLE
The tables_config table does not contain all PROPERTIES of a table

### ISSUE THREAD

**Issue by Jack1007** [StarRocks/starrocks#50286]
## Enhancement
For some purpose,I added "write_quorum" = "ONE" to a table to modify the write_quorum. After I changed the table properties,I found that the "write_quorum" property do not in the PROPERTIES field of the tables_config table.Maybe the tables_config does not contain all properties of a table? 

### example
starrocks version: 3.1.14
``` sql
-- show create table test.table1
CREATE TABLE `test`.`table1` (
  `id` int(11) NOT NULL COMMENT "用户 ID",
  `name` varchar(65533) NULL DEFAULT "" COMMENT "用户姓名",
  `score` int(11) NOT NULL DEFAULT "0" COMMENT "用户得分"
) ENGINE=OLAP 
PRIMARY KEY(`id`)
DISTRIBUTED BY HASH(`id`)
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "false",
"write_quorum" = "ONE",
"compression" = "LZ4"
);
```
select * from information_schema.tables_config where TABLE_NAME = 'table1'\G
```
     TABLE_SCHEMA: test
       TABLE_NAME: table1
     TABLE_ENGINE: OLAP
      TABLE_MODEL: PRIMARY_KEYS
      PRIMARY_KEY: `id`
    PARTITION_KEY: 
   DISTRIBUTE_KEY: `id`
  DISTRIBUTE_TYPE: HASH
DISTRIBUTE_BUCKET: 0
         SORT_KEY: `id`
       PROPERTIES: {"enable_persistent_index":"false","replication_num":"3","compression":"LZ4","in_memory":"false"}
         TABLE_ID: 373208
```
The PROPERTIES field of tables_config miss the "write_quorum" property. Hope to Enhance the PROPERTIES of tables_config.
