### ISSUE TITLE
3.3.3版本存算分离集群， brokerload 作业 卡在99%

### ISSUE THREAD

**Issue by lldlhd** [StarRocks/starrocks#54042]
集群规模： 3f   8cn
broker load 作业卡在 PREPARED 状态， LOAD:99% 一直是99%
![image](https://github.com/user-attachments/assets/f10eacc0-efda-401b-8127-5029176c9143)

这个导入表对应的partition 一直报这个错 fe
`[PublishVersionDaemon.publishPartitionBatch():556] Fail to publish partition 18910655 of txnIds [5989381, 5989397, 5989396, 5989399, 5989400, 5989398]: com.starrocks.rpc.RpcException: Fail to publish version for tablets [18910669]: The previous publish version task for tablet 18910669 has not finished. You can ignore this error and the task will retry later., host: starrocks-cn-3.starrocks-cn-search.starrocks-f5c07677-c7f7.svc.cluster.local`

cn中也一直打印日志
`I20241217 19:41:21.732686 139944242693696 transactions.cpp:125] Skipped publish version because target metadata found in cache. tablet_id=18910669 base_version=1 new_version=2 txns=txn_id: 5989340`

这两个日志怎么同时发生的。。。。
![image](https://github.com/user-attachments/assets/95f41724-f00b-4ad8-8e42-eb9328b705bb)

**Comment by luohaha** [comment]
Could you send us be.INFO?

**Comment by lldlhd** [comment]
[下载地址](https://ai-hanhai-train.ks3-cn-beijing.ksyuncs.com/cn.INFO)

**Comment by luohaha** [comment]
And upgrade to latest 3.3.7, we had fix some deadlock issues that.

**Comment by lldlhd** [comment]
> You can get a pstack of this BE, and restart it, maybe it is deadlock.

Restarting does not solve this problem

**Comment by lldlhd** [comment]
What is the origin of this loop and is there any way to solve it

**Comment by luohaha** [comment]
Could you send me the stack ?

**Comment by luohaha** [comment]
Have you found stack like this:
![image](https://github.com/user-attachments/assets/a716107e-cd2e-4d19-a6ea-726a122c6000)

**Comment by lldlhd** [comment]
我应该怎么获取这个？ 可以加微信私聊一下么？  plyl_188

**Comment by luohaha** [comment]
![image](https://github.com/user-attachments/assets/de78e026-397b-4143-9663-69bb9d77495e)
Try to ingest 400GB data.

```
mysql> show proc '/dbs/user_tag_all_weighted_enum_array/user_tag_all_weighted_enum_array/partitions'\G
*************************** 1. row ***************************
    PartitionId: 18910674
  PartitionName: user_tag_all_weighted_enum_array
 CompactVersion: 8681
 VisibleVersion: 8891
    NextVersion: 8897
          State: NORMAL
   PartitionKey: 
          Range: 
DistributionKey: tag_id
        Buckets: 16
       DataSize: 0B
       RowCount: 0
EnableDataCache: true
     AsyncWrite: false
          AvgCS: 1045.50
          P50CS: 0.00
          MaxCS: 16316.00
    DataVersion: 8748
   VersionEpoch: 326956467215138816
 VersionTxnType: TXN_NORMAL
1 row in set (0.00 sec)
```
but there are only 16 buckets in this table, and it is data skew:
```
          AvgCS: 1045.50
          P50CS: 0.00
          MaxCS: 16316.00
```

Suggestions:
1. recreate table with correct bucket number and bucket key.
2. upgrade to 3.3.7 later.
