### ISSUE TITLE
Make information_schema.routine_load_jobs schema consistent with show routine load

### ISSUE THREAD

**Issue by wyb** [StarRocks/starrocks#55118]
## Enhancement
Some columns are not in the system table, such as `TimestampProgress, LatestSourcePosition`

```
mysql> select * from information_schema.routine_load_jobs where id = 3175854\G
*************************** 1. row ***************************
                      ID: 3175854
                    NAME: label0
             CREATE_TIME: 2025-01-14 12:33:38
              PAUSE_TIME: NULL
                END_TIME: NULL
                 DB_NAME: kafka_test
              TABLE_NAME: largeint_test
                   STATE: RUNNING
        DATA_SOURCE_TYPE: KAFKA
        CURRENT_TASK_NUM: 1
          JOB_PROPERTIES: {}
  DATA_SOURCE_PROPERTIES: {}
       CUSTOM_PROPERTIES: {"group.id":"label0_67d7accf-4fbb-45f4-bbb1-da8e3e20d1e0"}
              STATISTICS: {}
                PROGRESS: {"0":"1"}
REASONS_OF_STATE_CHANGED:
          ERROR_LOG_URLS: NULL
            TRACKING_SQL: NULL
               OTHER_MSG: 
1 row in set (0.11 sec)

mysql> show routine load\G
*************************** 1. row ***************************
                  Id: 3175854
                Name: label0
          CreateTime: 2025-01-14 12:33:38
           PauseTime: NULL
             EndTime: NULL
              DbName: kafka_test
           TableName: largeint_test
               State: RUNNING
      DataSourceType: KAFKA
      CurrentTaskNum: 1
       JobProperties: {}
DataSourceProperties: {}
    CustomProperties: {"group.id":"label0_67d7accf-4fbb-45f4-bbb1-da8e3e20d1e0"}
           Statistic: {}
            Progress: {"0":"1"}
   TimestampProgress: {}
ReasonOfStateChanged:
        ErrorLogUrls:
         TrackingSQL:
            OtherMsg: 
LatestSourcePosition: {"0":"2"}
1 row in set (0.00 sec)
```
