### ISSUE TITLE
Add partition offset lag column in show routine load and information_schema.routine_load_jobs

### ISSUE THREAD

**Issue by wyb** [StarRocks/starrocks#55119]
## Enhancement

there are two kafka partition offset related columns in show routine load.
`Progress`:  The progress (measured in the offset) of consuming messages in partitions of the topic.
`LatestSourcePosition`: The position of latest message in each partition of the topic, which helps check the latencies of data loading.

```
mysql> show routine load\G
*************************** 1. row ***************************
                  Id: 3175854
                Name: label0
          CreateTime: 2025-01-14 12:33:38
           PauseTime: NULL
             EndTime: NULL
              DbName: kafka_test
           TableName: largeint_test
               State: RUNNING
      DataSourceType: KAFKA
      CurrentTaskNum: 1
       JobProperties: {}
DataSourceProperties: {}
    CustomProperties: {"group.id":"label0_67d7accf-4fbb-45f4-bbb1-da8e3e20d1e0"}
           Statistic: {}
            Progress: {"0":"1"}
   TimestampProgress: {}
ReasonOfStateChanged:
        ErrorLogUrls:
         TrackingSQL:
            OtherMsg: 
LatestSourcePosition: {"0":"2"}
```

want to add a new `OffsetLag` column, so that can easily know the offset lag, especially when there are many kafka topic partitions.
