### ISSUE TITLE
YAML file is incorrectly configured and should be reported during precheck

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5582]
### Steps to reproduce the behavior (Required)
1. 
vim test04.yaml
```
global:
    user: "starrocks"
    ssh_port: 22

fe_servers:
  - host: 192.168.88.83
    ssh_port: 22
    http_port: 8031
    rpc_port: 9021
    query_port: 9031
    edit_log_port: 9011
    deploy_dir: /opt/starrocks04/fe
    meta_dir: /data/starrocks04/fe/meta
    log_dir: /data/starrocks04/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"
      sys_log_delete_age: "1d"
  - host: 192.168.88.84
    ssh_port: 22
    http_port: 8031
    rpc_port: 9021
    query_port: 9031
    edit_log_port: 9011
    deploy_dir: /opt/starrocks04/fe
    meta_dir: /data/starrocks04/fe/meta
    log_dir: /data/starrocks04/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_delete_age: "2d"
  - host: 192.168.88.84
    ssh_port: 22
    http_port: 8031
    rpc_port: 9021
    query_port: 9031
    dit_log_port: 9011
    deploy_dir: /opt/starrocks04/fe
    meta_dir: /data/starrocks04/fe/meta
    log_dir: /data/starrocks04/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_delete_age: "3d"
be_servers:
  - host: 192.168.88.84
    ssh_port: 22
    be_port: 9061
    webserver_port: 8041
    heartbeat_service_port: 9051
    brpc_port: 8061
    deploy_dir : /opt/starrocks04/be
    storage_dir: /data/starrocks04/be/storage
    log_dir: /data/starrocks04/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
be_servers:
  - host: 192.168.88.83
    ssh_port: 22
    be_port: 9061
    webserver_port: 8041
    heartbeat_service_port: 9051
    brpc_port: 8061
    deploy_dir : /opt/starrocks04/be
    storage_dir: /data/starrocks04/be/storage
    log_dir: /data/starrocks04/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
be_servers:
  - host: 192.168.88.85
    ssh_port: 22
    be_port: 9061
    webserver_port: 8041
    heartbeat_service_port: 9051
    brpc_port: 8061
    deploy_dir : /opt/starrocks04/be
    storage_dir: /data/starrocks04/be/storage
    log_dir: /data/starrocks04/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
```
2.
[root@nd1 ~]# ssh-copy-id starrocks@nd3
[root@nd1 ~]# ssh-copy-id starrocks@nd4
[root@nd1 ~]# ssh-copy-id starrocks@nd5
3.
[root@nd3 opt]# mkdir /opt/starrocks04 && chown starrocks:starrocks /opt/starrocks04
[root@nd3 opt]# mkdir -p /data/starrocks04 && chown starrocks:starrocks /data/starrocks04
[root@nd4 opt]# mkdir /opt/starrocks04 && chown starrocks:starrocks /opt/starrocks04
[root@nd4 opt]# mkdir -p /data/starrocks04 && chown starrocks:starrocks /data/starrocks04
[root@nd5 opt]# mkdir /opt/starrocks04 && chown starrocks:starrocks /opt/starrocks04
[root@nd5 opt]# mkdir -p /data/starrocks04 && chown starrocks:starrocks /data/starrocks04
4.
Execute on the deployment machine：
./sr-ctl-without-debug cluster deploy test04 v2.0.1 test04.yaml
### Expected behavior (Required)
deploy failed and should be reported during precheck

### Real behavior (Required)
deploy failed ，after execute deployment command report error
![image](https://user-images.githubusercontent.com/57162397/165474218-8ff1a626-811b-4b71-9837-f77978d05e7f.png)
