### ISSUE TITLE
The user-defined query_port does not take effect

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5605]
### Steps to reproduce the behavior (Required)
1. 
vim test04.yaml
```
global:
    user: "starrocks"
    ssh_port: 22

fe_servers:
  - host: 192.168.88.83
    ssh_port: 22
    http_port: 8032
    rpc_port: 9022
    query_port: 9032
    edit_log_port: 9012
    deploy_dir: /opt/starrocks22/fe
    meta_dir: /data/starrocks22/fe/meta
    log_dir: /data/starrocks22/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"
      sys_log_delete_age: "1d"
  - host: 192.168.88.84
    ssh_port: 22
    http_port: 8032
    rpc_port: 9022
    query_port: 9032
    edit_log_port: 9012
    deploy_dir: /opt/starrocks22/fe
    meta_dir: /data/starrocks22/fe/meta
    log_dir: /data/starrocks22/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_delete_age: "2d"
  - host: 192.168.88.85
    ssh_port: 22
    http_port: 8032
    rpc_port: 9022
    query_port: 9032
    edit_log_port: 9012
    deploy_dir: /opt/starrocks22/fe
    meta_dir: /data/starrocks22/fe/meta
    log_dir: /data/starrocks22/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_delete_age: "3d"
be_servers:
  - host: 192.168.88.84
    ssh_port: 22
    be_port: 9062
    webserver_port: 8042
    heartbeat_service_port: 9052
    brpc_port: 8062
    deploy_dir : /opt/starrocks22/be
    storage_dir: /data/starrocks22/be/storage
    log_dir: /data/starrocks22/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
be_servers:
  - host: 192.168.88.83
    ssh_port: 22
    be_port: 9062
    webserver_port: 8042
    heartbeat_service_port: 9052
    brpc_port: 8062
    deploy_dir : /opt/starrocks22/be
    storage_dir: /data/starrocks22/be/storage
    log_dir: /data/starrocks22/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
be_servers:
  - host: 192.168.88.85
    ssh_port: 22
    be_port: 9062
    webserver_port: 8042
    heartbeat_service_port: 9052
    brpc_port: 8062
    deploy_dir : /opt/starrocks22/be
    storage_dir: /data/starrocks22/be/storage
    log_dir: /data/starrocks22/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
```
2.
[root@nd1 ~]# ssh-copy-id starrocks@nd3
[root@nd1 ~]# ssh-copy-id starrocks@nd4
[root@nd1 ~]# ssh-copy-id starrocks@nd5
3.
[root@nd3 opt]# mkdir /opt/starrocks22 && chown starrocks:starrocks /opt/starrocks22
[root@nd3 opt]# mkdir -p /data/starrocks22 && chown starrocks:starrocks /data/starrocks22
[root@nd4 opt]# mkdir /opt/starrocks22 && chown starrocks:starrocks /opt/starrocks22
[root@nd4 opt]# mkdir -p /data/starrocks22 && chown starrocks:starrocks /data/starrocks22
[root@nd5 opt]# mkdir /opt/starrocks22 && chown starrocks:starrocks /opt/starrocks22
[root@nd5 opt]# mkdir -p /data/starrocks22 && chown starrocks:starrocks /data/starrocks22
4.
Execute on the deployment machine：
./sr-ctl-without-debug cluster deploy test22 v2.0.1 test22.yaml
### Expected behavior (Required)
deploy success

### Real behavior (Required)
deploy failed
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/57162397/165526420-44bfd723-1736-4a2c-a43d-45dc3b215811.png">
<img width="970" alt="image" src="https://user-images.githubusercontent.com/57162397/165526498-02c15511-f66b-4b04-88f7-dbbead473234.png">
