### ISSUE TITLE
meta.yaml is lost after the cluster is started

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5643]
### Steps to reproduce the behavior (Required)
1. 
vim test04.yaml
```
global:
    user: "starrocks"
    ssh_port: 22

fe_servers:
  - host: 192.168.88.83
    ssh_port: 22
    http_port: 8030
    rpc_port: 9020
    query_port: 9030
    edit_log_port: 9010
    deploy_dir: /opt/starrockslcy/fe
    meta_dir: /data/starrockslcy/fe/meta
    log_dir: /data/starrockslcy/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"
      sys_log_delete_age: "1d"
  - host: 192.168.88.84
    ssh_port: 22
    http_port: 8030
    rpc_port: 9020
    query_port: 9030
    edit_log_port: 9010
    deploy_dir: /opt/starrockslcy/fe
    meta_dir: /data/starrockslcy/fe/meta
    log_dir: /data/starrockslcy/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_delete_age: "2d"
  - host: 192.168.88.85
    ssh_port: 22
    http_port: 8030
    rpc_port: 9020
    query_port: 9030
    edit_log_port: 9010
    deploy_dir: /opt/starrockslcy/fe
    meta_dir: /data/starrockslcy/fe/meta
    log_dir: /data/starrockslcy/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_delete_age: "3d"
be_servers:
  - host: 192.168.88.84
    ssh_port: 22
    be_port: 9060
    webserver_port: 8040
    heartbeat_service_port: 9050
    brpc_port: 8060
    deploy_dir : /opt/starrockslcy/be
    storage_dir: /data/starrockslcy/be/storage
    log_dir: /data/starrockslcy/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
```
2.
[root@nd1 ~]# ssh-copy-id starrocks@nd3
[root@nd1 ~]# ssh-copy-id starrocks@nd4
[root@nd1 ~]# ssh-copy-id starrocks@nd5
3.
[root@nd3 opt]# mkdir /opt/starrockslcy && chown starrocks:starrocks /opt/starrockslcy
[root@nd3 opt]# mkdir -p /data/starrockslcy && chown starrocks:starrocks /data/starrockslcy
[root@nd4 opt]# mkdir /opt/starrockslcy && chown starrocks:starrocks /opt/starrockslcy
[root@nd4 opt]# mkdir -p /data/starrockslcy && chown starrocks:starrocks /data/starrockslcy
[root@nd5 opt]# mkdir /opt/starrockslcy && chown starrocks:starrocks /opt/starrockslcy
[root@nd5 opt]# mkdir -p /data/starrockslcy && chown starrocks:starrocks /data/starrockslcy
4.
Execute on the deployment machine：
./sr-ctl-without-debug cluster deploy testlcy v2.0.1 testlcy.yaml
5.
[testlcy@nd1 ~]$ ./sr-ctl cluster stop testlcy --node 192.168.88.83:9010
[testlcy@nd1 ~]$ ./sr-ctl cluster stop testlcy --node 192.168.88.84:9010
6.
[testlcy@nd1 ~]$ ./sr-ctl cluster start testlcy --role FE
7.
./sr-ctl cluster stop --node 192.168.88.85:9010
### Expected behavior (Required)
stop fe node success

### Real behavior (Required)
stop fe node failed
![image](https://user-images.githubusercontent.com/57162397/165716636-aa3b9158-86ba-441f-988a-974a903d5853.png)
