### ISSUE TITLE
starrocks cn 节点memory内存统计异常

### ISSUE THREAD

**Issue by auguszero** [StarRocks/starrocks#56739]
## 基础信息 
版本: 3.3.7 
存算分离版本
### cn节点基础配置
```yaml
# 系统日志分卷的模式。有效值包括 TIME-DAY、TIME-HOUR 和 SIZE-MB- 大小。默认值表示日志被分割成大小为 1GB 的日志卷。
      #20241218更新
      #sys_log_roll_mode = TIME-DAY  
      sys_log_roll_mode = SIZE-MB-1024
      # 日志卷保留的数目。
      #20241218更新 10->1
      sys_log_roll_num = 4
      # 导入线程数，用于处理 NORMAL 优先级任务。
      push_worker_count_normal_priority = 6
      # 导入线程数，用于处理 HIGH 优先级任务。
      push_worker_count_high_priority = 6
      # 单节点上所有的导入线程占据的内存上限比例。
      load_process_max_memory_limit_percent = 90
      
      # 20241204更新
      # 每个 Store 用以 Flush MemTable 的线程数。
      flush_thread_num_per_store = 8
      storage_page_cache_limit = 5%
      
      #20241203
      query_mem_limit = 6442450944
      mem_limit = 105%
      query_max_memory_limit_percent = 60
      
      #20250206
      #memtable flush 的大小  25MB 
      l0_max_mem_usage = 26214400
      # update 可使用的内存大小 ， 默认值为60% ，当前由于update memory 存在内存统计不准确的情况，所以需要适当的减少内存占比，减少对集群的影响
      update_memory_limit_percent = 25
      
      #######======= 动态参数 =======#######  
      # Update Cache 的过期时间。
      # 20250203 更新时间到2min,大多数更新场景均在单个分区内快速更新结束，故可以缩短具体时间
      update_cache_expire_sec = 120
      # 流式导入单个文件大小的上限。自 3.0 版本起，默认值由 10240 变为 102400。单位MB
      streaming_load_max_mb = 102400
      
      sys_log_level = INFO
      # ports for admin, web, heartbeat service
      thrift_port = 9060
      webserver_port = 8040
      heartbeat_service_port = 9050
      brpc_port = 8060
      # 存算分离配置内容
      # 存算分离模式下是否使用 Data Cache。true 表示启用该功能，false 表示禁用。
      # 当前选择关闭 是因为在load stream时会将大部分数据缓存在本地，从而导致本地pvc数据过大，且不会根据数据进行删除。
      
      #20241030更新
      starlet_use_star_cache = true
      starlet_star_cache_disk_size_percent = 8
      
      # 存算分离集群 Compaction 任务在远程 FS 读 I/O 阶段的 Buffer 大小。默认值为 1MB。您可以适当增大该配置项取值以加速 Compaction 任务。 当前为10MB
      lake_compaction_stream_buffer_size_bytes=10485760
      
      # 数据导入The reservation time for the files produced by small-scale loadings. 
      load_data_reserve_hours = 1
      
      # compaction 优化 降低合并线程数, 降低单次小合并的的segment数量，增高compaction合并成功率
      max_cumulative_compaction_num_singleton_deltas=100
      compact_threads=16
      compact_thread_pool_queue_size=100
      lake_enable_vertical_compaction_fill_data_cache=true
``` 
### fe节点基础配置
```yaml 
# 20241030更新
      # fe配置 非动态 类型 string 
      audit_log_modules = slow_query
      # fe配置 动态配置 类型 Long
      qe_slow_log_ms = 30000
      
      #20241122更新
      #审计日志，默认保留30d
      audit_log_delete_age: 3d
      #系统日志，默认保留7d
      sys_log_delete_age: 3d
      #dump日志，默认保留7d
      dump_log_delete_age: 3d
      max_automatic_partition_number = 16384
      
      # MySQL 服务器中用于处理 I/O 事件的最大线程数。
      mysql_service_io_threads_num = 8
      # FE 所在 StarRocks 集群中，Leader FE 上的日志刷盘方式。该参数仅在当前 FE 为 Leader 时有效。
      # SYNC：事务提交时同步写日志并刷盘。
      # NO_SYNC：事务提交时不同步写日志。
      # WRITE_NO_SYNC：事务提交时同步写日志，但是不刷盘。
      master_sync_policy = SYNC
      # 是否开启锁管理。lock manager 可以对锁实现集中管理，例如控制是否将元数据锁的粒度从库级别细化为表级别。
      lock_manager_enabled = true
      # 是否将元数据锁的粒度从库级别细化为表级别。元数据锁细化为表级别后，可以减小锁冲突和竞争，提高导入和查询的并发性能。该参数只在 lock_manager_enabled 开启的前提下生效。
      lock_manager_enable_using_fine_granularity_lock = true
      # 是否开启动态分区功能。打开后，您可以按需为新数据动态创建分区，同时 StarRocks 会⾃动删除过期分区，从而确保数据的时效性。
      dynamic_partition_enable = true
      # 如果一条 HTTP 请求的时间超过了该参数指定的时长，会生成日志来跟踪该请求。单位毫秒
      http_slow_request_threshold_ms = 5000
      
      # 用于配置自动全量采集的起始时间。取值范围：00:00:00 ~ 23:59:59。
      statistic_auto_analyze_start_time = 06:00:00
      statistic_auto_analyze_end_time = 22:00:00
      
      #######======= 动态参数 =======####### 
      # 当空表第一次导入数据时，是否自动触发统计信息采集。如果一张表包含多个分区，只要是某个空的分区第一次导入数据，都会触发该分区的统计信息采集。如果系统频繁创建新表并且导入数据，会存在一定内存和 CPU 开销。
      # 导入历史数据时，将此参数设置为false，导入完成后再将此参数设置为true。
      enable_statistic_collect_on_first_load = true
      # 是否在导入事务 publish 阶段同步执行 apply 任务，仅适用于主键表。有效值：
      # TRUE：导入事务 publish 阶段同步执行 apply 任务，
          #   即 apply 任务完成后才会返回导入事务 publish 成功，此时所导入数据真正可查。
          #   因此当导入任务一次导入的数据量比较大，或者导入频率较高时，开启该参数可以提升查询性能和稳定性，但是会增加导入耗时。
      # FALSE：在导入事务 publish 阶段异步执行 apply 任务，
          #   即在导入事务 publish 阶段 apply 任务提交之后立即返回导入事务 publish 成功，然而此时导入数据并不真正可查。
          #   这时并发的查询需要等到 apply 任务完成或者超时，才能继续执行。因此当导入任务一次导入的数据量比较大，或者导入频率较高时，关闭该参数会影响查询性能和稳定性。
      # 3.2 版本生效，当前版本3.1-stable 可能生效 
      enable_sync_publish = true
``` 

## 现象
1.  cn节点重启时，若无任何upsert操作，则cn 内存管理页面 ， mem_tracker  统计数据基本正常 ，不存在大量gap 
2. 当存在大批量 更新操作(streamload )，cn内存管理页面 ，统计页面存在大量gap。 level1 内存>> sum(level2 内存)
