### ISSUE TITLE
Data gone and cluster won't start after all pods restart at the same time

### ISSUE THREAD

**Issue by ItielOlenick** [StarRocks/starrocks#56768]
### Steps to reproduce the behavior (Required)
1. Create a starrocks deployment using the operator helm chart
2. Delete all FE and BE pods at the same time

### Expected behavior (Required)
After all FE and BE pods come back up the cluster should be up and running.

### Real behavior (Required)
Only one FE pod is up, password for the root user changed and all data is lost.

### StarRocks version (Required)
3.3.7-00177de

**Comment by sida-shen** [comment]
@ItielOlenick Is this shared nothing? If that is the case, the data is gone when you drop the pods with the EBS volume gone.

**Comment by ItielOlenick** [comment]
Yes, shared nothing deployment.
The sts is still intact. PVC wasn't deleted.
Only pods were killed.

**Comment by nshangyiming** [comment]
If the PVC is still there, i think there is still a chance to recover the cluster. @gengjun-git could you help @ItielOlenick and give some instructions on how to recover it.

**Comment by gengjun-git** [comment]
@ItielOlenick Hello, can you show us the log at the restart time

**Comment by gengjun-git** [comment]
2025-03-11 07:31:33.628Z INFO (main|1) [NodeMgr.getClusterIdAndRoleOnStartup():314] very first time to start this node. role: FOLLOWER, node name: starrocks-fe-0.starrocks-fe-search.data.svc.cluster.local_9010_1741678293616
@ItielOlenick  Are you sure that the data in the meta directory still exists after deleting the pod? The above log shows that this is the first time this node is started, which means that the historical data has been lost.

**Comment by ItielOlenick** [comment]
What would delete the data other than one of the starrocks components?
Again, all that is done is delete the pods.

**Comment by yandongxiao** [comment]
If possible, could you share your values.yaml file? We can confirm your deployment details.

**Comment by ItielOlenick** [comment]
Sure
```yaml
starrocks:
  starrocksCluster:
    componentValues:
      serviceAccount: "starrocks"

  nameOverride: "starrocks"
  initPassword:
    passwordSecret: starrocks-init-password
    enabled: true
  timeZone: Etc/UTC

  starrocksFESpec:
    image:
      repository: xxx.dkr.ecr.us-east-1.amazonaws.com/docker/starrocks/fe-ubuntu
      tag: "3.3.7"
    replicas: 3
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 8
      memory: 16Gi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - fe
            topologyKey: "kubernetes.io/hostname"
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        external-dns.alpha.kubernetes.io/public-only: "true"
        external-dns.alpha.kubernetes.io/hostname: ""
        service.beta.kubernetes.io/aws-load-balancer-security-group-prefix-lists: ""
        alb.ingress.kubernetes.io/scheme: internet-facing # External dns is filtering for this annotation
      loadBalancerSourceRanges: []
      type: LoadBalancer

  starrocksBeSpec:
    image:
      repository: xxx.dkr.ecr.us-east-1.amazonaws.com/docker/starrocks/be-ubuntu
      tag: "3.3.7"
    replicas: 3
    limits:
      cpu: 8
      memory: 32Gi
    requests:
      cpu: 8
      memory: 32Gi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - be
            topologyKey: "kubernetes.io/hostname"
    storageSpec:
      name: starrocks-be
      storageClassName: gp3-for-starrocks
      storageSize: 100Gi
      logStorageSize: 20Gi

  starrocksFeProxySpec:
    enabled: false
    
```

**Comment by yandongxiao** [comment]
I think I know why the data loss occurred, `storageSpec` is only configured on the BE Module, and there is no related configuration on FE. The Operator will use emptyDir as the data storage for FE Meta Data by default. Although multiple FEs can form a high-availability version, we strongly recommend that relevant persistence be done for FE Meta Data as well. This is an important means to ensure that Meta Data is not lost. 

If you are using starrocks chart instead of kube-starrocks Chart, I suggest you refer to the configuration here: https://github.com/StarRocks/starrocks-kubernetes-operator/blob/509a0a4aab1561691ec3e2550b2fff3b18f2f443/helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml#L304-L334

**Comment by ItielOlenick** [comment]
Got it. I am using https://starrocks.github.io/starrocks-kubernetes-operator.
So this should be sufficient?

```yaml
...
  starrocksFESpec:
    storageSpec:
      name: starrocks-be
      storageClassName: gp3-for-starrocks
      storageSize: 10Gi
      logStorageSize: 5Gi
...
```

**Comment by yandongxiao** [comment]
```
  starrocksFESpec:
    storageSpec:
      name: starrocks-fe     # here
      storageClassName: gp3-for-starrocks
      storageSize: 10Gi
      logStorageSize: 5Gi
```

You can add this part to redeploy your SR cluster, and I think this problem will be fixed.
