### ISSUE TITLE
SSH mutual trust is not established ，Optimized deployment prompts

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5744]
### Steps to reproduce the behavior (Required)
1. 
```
[root@nd3 ~]# groupadd test222
[root@nd3 ~]# useradd -g test222 test22
```
2.
```
[root@nd3 ~]# mkdir /opt/starrocks123 && chown test222:test222 /opt/starrocks123
[root@nd3 ~]# mkdir -p /data/starrocks222 && chown test222:test222 /data/starrocks222
```
3.
vim test123.yaml
```
global:
    user: "test222"
    ssh_port: 22

fe_servers:
  - host: 192.168.88.83
    ssh_port: 22
    http_port: 8031
    rpc_port: 9021
    query_port: 9031
    edit_log_port: 9011
    deploy_dir: /opt/starrocks222/fe
    meta_dir: /data/starrocks222/fe/meta
    log_dir: /data/starrocks222/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"
      sys_log_delete_age: "1d"
be_servers:
  - host: 192.168.88.83
    ssh_port: 22
    be_port: 9061
    webserver_port: 8041
    heartbeat_service_port: 9051
    brpc_port: 8061
    deploy_dir : /opt/starrocks222/be
    storage_dir: /data/starrocks222/be/storage
    log_dir: /data/starrocks222/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
```
4.
Execute on the deployment machine：
./main-0505-2 cluster deploy test123 v2.0.1 test123.yaml

### Expected behavior (Required)
deploy failed Optimized deployment prompts

### Real behavior (Required)
deploy failed Duplicate prompt message
![image](https://user-images.githubusercontent.com/57162397/166888602-4952a593-8c19-48ab-a901-3f4ded62804a.png)
