### ISSUE TITLE
Only one FE or BE should not be allowed to scale-in

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5765]
### Steps to reproduce the behavior (Required)
1. 
```
[root@nd3 ~]# groupadd test222
[root@nd3 ~]# useradd -g test222 test22
```
2.
```
[root@nd3 ~]# mkdir /opt/starrocks123 && chown test222:test222 /opt/starrocks123
[root@nd3 ~]# mkdir -p /data/starrocks222 && chown test222:test222 /data/starrocks222
```
3.
vim test123.yaml
```
global:
    user: "test222"
    ssh_port: 22

fe_servers:
  - host: 192.168.88.83
    ssh_port: 22
    http_port: 8031
    rpc_port: 9021
    query_port: 9031
    edit_log_port: 9011
    deploy_dir: /opt/starrocks222/fe
    meta_dir: /data/starrocks222/fe/meta
    log_dir: /data/starrocks222/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"
      sys_log_delete_age: "1d"
be_servers:
  - host: 192.168.88.83
    ssh_port: 22
    be_port: 9061
    webserver_port: 8041
    heartbeat_service_port: 9051
    brpc_port: 8061
    deploy_dir : /opt/starrocks222/be
    storage_dir: /data/starrocks222/be/storage
    log_dir: /data/starrocks222/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
```
4.
```
[test123@nd1 ~]$ ssh-copy-id test222@nd3
```
5.
Execute on the deployment machine：
./main-0505-2 cluster deploy test123 v2.0.1 test123.yaml
```
[test123@nd1 ~]$ ./main-0505-2 cluster display test123
[20220505-202236  OUTPUT] Display cluster [clusterName = test123]
clusterName = test123
clusterVerison =
ID                          ROLE    HOST                  PORT             STAT        DATADIR                                             DEPLOYDIR
--------------------------  ------  --------------------  ---------------  ----------  --------------------------------------------------  --------------------------------------------------
192.168.88.83:9011          FE      192.168.88.83         9011/9031        UP          /opt/starrocks222/fe                                /data/starrocks222/fe/meta
192.168.88.84:9061          BE      192.168.88.84         9061/9051        UP          /opt/starrocks222/be                                /data/starrocks222/be/storage
[test123@nd1 ~]$ ./main-0505-2 cluster scale-in test123 --node 192.168.88.83:9011
```

### Expected behavior (Required)
Only one FE or BE should not be allowed to scale-in

### Real behavior (Required)
scale-in  FE success
![image](https://user-images.githubusercontent.com/57162397/166923248-36ad2655-f707-4b22-b548-7bddabcbbb83.png)
