### ISSUE TITLE
Deployment/scale-inscale-in/scale-out should maintain only one YAMl file

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5779]
### Steps to reproduce the behavior (Required)
After the deployment is complete, you need to create a new file for scale-in or scale-out
1.
The premise
./main-0505-2 cluster deploy test123 v2.0.1 test123.yaml
The cluster has been deploy
2.
vim test+.yaml
```
be_servers:
  - host: 192.168.88.84
    ssh_port: 22
    be_port: 9061
    webserver_port: 8041
    heartbeat_service_port: 9051
    brpc_port: 8061
    deploy_dir : /opt/starrocks222/be
    storage_dir: /data/starrocks222/be/storage
    log_dir: /data/starrocks222/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
```
./main-0505-2 cluster scale-out test123 test+.yaml
### Expected behavior (Required)
should maintain only one YAML file
### Real behavior (Required)
Maintain multiple YAML files
