### ISSUE TITLE
【易用性】permissions  output a suggestion for weighting

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5784]
### Steps to reproduce the behavior (Required)
After the deployment is complete, you need to create a new file for scale-in or scale-out
1.
The premise
./main-0505-2 cluster deploy test123 v2.0.1 test123.yaml
The cluster has been deploy
2.
nd5
mkdir /opt/starrocks222 && chown test222:test222 /opt/starrocks222
mkdir -p /data/starrocks222 && chown test222:test222 /data/starrocks222
3.
vim test_fe_nd5.yaml
```
fe_servers:
  - host: 192.168.88.85
    ssh_port: 22
    http_port: 8031
    rpc_port: 9021
    query_port: 9031
    edit_log_port: 9011
    deploy_dir: /opt/starrocks222/fe
    meta_dir: /data/starrocks222/fe/meta
    log_dir: /data/starrocks222/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"
      sys_log_delete_age: "3d"
```
./main-0505-2 cluster scale-out test123 test_fe_nd5.yaml
### Expected behavior (Required)
If you don't have permission ，output a suggestion for weighting
### Real behavior (Required)
deploy failed
The permission needs to be granted again
[root@nd5 data]# chown -R test222:test222 /opt/starrocks222
[root@nd5 data]# chown -R test:test222 /data/starrocks222
![d2rHHLr7ka](https://user-images.githubusercontent.com/57162397/167089370-05b53c60-1723-4da8-8ef2-082b3d828e64.png)
