### ISSUE TITLE
The number of nodes to be scale-out  is different from the actual number

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5785]
### Steps to reproduce the behavior (Required)
After the deployment is complete, you need to create a new file for scale-in or scale-out
1.
The premise
./main-0505-2 cluster deploy test123 v2.0.1 test123.yaml
The cluster has been deploy
2.
nd5
```
mkdir /opt/starrocks222 && chown test222:test222 /opt/starrocks222
mkdir -p /data/starrocks222 && chown test222:test222 /data/starrocks222
```
3.
vim test_be_nd4_nd5.yaml
```
be_servers:
  - host: 192.168.88.84
    ssh_port: 22
    be_port: 9061
    webserver_port: 8041
    heartbeat_service_port: 9051
    brpc_port: 8061
    deploy_dir : /opt/starrocks222/be
    storage_dir: /data/starrocks222/be/storage
    log_dir: /data/starrocks222/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
be_servers:
  - host: 192.168.88.85
    ssh_port: 22
    be_port: 9061
    webserver_port: 8041
    heartbeat_service_port: 9051
    brpc_port: 8061
    deploy_dir : /opt/starrocks222/be
    storage_dir: /data/starrocks222/be/storage
    log_dir: /data/starrocks222/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
```
./main-0505-2 cluster scale-out test123 test_be_nd4_nd5.yaml
### Expected behavior (Required)
deploy success and  the number of nodes is the same as the actual number
### Real behavior (Required)
The number of nodes to be scale-out  is different from the actual number
![image](https://user-images.githubusercontent.com/57162397/167092948-8804e12d-9a7d-488a-a745-bc1d8352ab11.png)
