### ISSUE TITLE
【star up】The command should be unified

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5902]
### Steps to reproduce the behavior (Required)
1.
The premise
vim test123.yaml
```
global:
    user: "test222"
    ssh_port: 22

fe_servers:
  - host: 192.168.88.83
    ssh_port: 22
    http_port: 8031
    rpc_port: 9021
    query_port: 9031
    edit_log_port: 9011
    deploy_dir: /opt/starrocks222/fe
    meta_dir: /data/starrocks222/fe/meta
    log_dir: /data/starrocks222/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"
      sys_log_delete_age: "1d"
  - host: 192.168.88.84
    ssh_port: 22
    http_port: 8031
    rpc_port: 9021
    query_port: 9031
    edit_log_port: 9011
    deploy_dir: /opt/starrocks222/fe
    meta_dir: /data/starrocks222/fe/meta
    log_dir: /data/starrocks222/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"
      sys_log_delete_age: "2d"
- host: 192.168.88.85
    ssh_port: 22
    http_port: 8031
    rpc_port: 9021
    query_port: 9031
    edit_log_port: 9011
    deploy_dir: /opt/starrocks222/fe
    meta_dir: /data/starrocks222/fe/meta
    log_dir: /data/starrocks222/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"
      sys_log_delete_age: "3d"
be_servers:
  - host: 192.168.88.83
    ssh_port: 22
    be_port: 9061
    webserver_port: 8041
    heartbeat_service_port: 9051
    brpc_port: 8061
    deploy_dir : /opt/starrocks222/be
    storage_dir: /data/starrocks222/be/storage
    log_dir: /data/starrocks222/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
```
./main-0505-2 cluster deploy test123 v2.0.1 test123.yaml
The cluster has been deploy

2. 
./main-0505-2 cluster test123 upgrade v2.1.3

### Expected behavior (Required)
star up cluster scale-in/scale-out/upgrade/downgrade  <cluster-name> <version>
### Real behavior (Required)
star up cluster <cluster-name> upgrade/downgrade   <version>
