### ISSUE TITLE
【star up】The cluster upgrade log and node_id fails

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#5906]
### Steps to reproduce the behavior (Required)
1.
The premise
vim test_long_keep.yaml
```
global:
    user: "test222"
    ssh_port: 22

fe_servers:
  - host: 192.168.88.83
    ssh_port: 22
    http_port: 8032
    rpc_port: 9022
    query_port: 9032
    edit_log_port: 9012
    deploy_dir: /opt/starrocks222/fe
    meta_dir: /data/starrocks222/fe/meta
    log_dir: /data/starrocks222/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"
      sys_log_delete_age: "1d"
be_servers:
  - host: 192.168.88.83
    ssh_port: 22
    be_port: 9062
    webserver_port: 8042
    heartbeat_service_port: 9052
    brpc_port: 8062
    deploy_dir : /opt/starrocks222/be
    storage_dir: /data/starrocks222/be/storage
    log_dir: /data/starrocks222/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
```
./main-0505-2 cluster deploy test_long_keep v2.1.3 test_long_keep.yaml
The cluster has been deploy

2. 
```
[test123@nd1 ~]$ ./main-0505-2 cluster test_long_keep upgrade v2.1.3
```

### Expected behavior (Required)
[20220510-153341  OUTPUT] Starting downgrade FE node. [feId = 192.168.88.83:9012]
### Real behavior (Required)
[20220510-155140  OUTPUT] Starting upgrade BE node. [feId = 0]
![image](https://user-images.githubusercontent.com/57162397/167579676-9f7821b8-1f73-4b47-85d6-0b87fffd9b6e.png)
