### ISSUE TITLE
Query cache does not work when query Parquet

### ISSUE THREAD

**Issue by hongbo-miao** [StarRocks/starrocks#59232]
### Steps to reproduce the behavior (Required)

```sql
-- Enable query cache
set global enable_query_cache=true;

-- Query Parquet file in S3
desc files (
  "aws.s3.region" = "us-west-2",
  "aws.s3.use_aws_sdk_default_behavior" = "true",
  "format" = "parquet",
  "path" = "s3://iot-data-bucket/motor.parquet"
);
```

However, when I run `show backends;`, DiskUsage still shows `0B/340GB`.
```
10001	kube-starrocks-be-0.kube-starrocks-be-search.production-horizon-starrocks.svc.cluster.local	9050	9060	8040	8060	2025-05-22 03:39:47	2025-05-22 04:23:38	true	false	false	69	0.000 B	490.993 GB	491.082 GB	0.02 %	0.02 %		3.3.14-2ce6e68	{"lastSuccessReportTabletsTime":"2025-05-22 04:22:48"}	490.993 GB	0.00 %	8	6.480GB	0	3.58 %	0.0 %	Status: Normal, DiskUsage: 0B/340GB, MemUsage: 0B/0B
10169	kube-starrocks-be-1.kube-starrocks-be-search.production-horizon-starrocks.svc.cluster.local	9050	9060	8040	8060	2025-05-22 03:40:02	2025-05-22 04:23:38	true	false	false	69	0.000 B	490.993 GB	491.082 GB	0.02 %	0.02 %		3.3.14-2ce6e68	{"lastSuccessReportTabletsTime":"2025-05-22 04:23:03"}	490.993 GB	0.00 %	8	6.480GB	0	4.16 %	0.0 %	Status: Normal, DiskUsage: 0B/340GB, MemUsage: 0B/0B
10167	kube-starrocks-be-2.kube-starrocks-be-search.production-horizon-starrocks.svc.cluster.local	9050	9060	8040	8060	2025-05-22 03:40:02	2025-05-22 04:23:38	true	false	false	69	0.000 B	490.993 GB	491.082 GB	0.02 %	0.02 %		3.3.14-2ce6e68	{"lastSuccessReportTabletsTime":"2025-05-22 04:23:03"}	490.993 GB	0.00 %	8	6.480GB	0	3.12 %	0.0 %	Status: Normal, DiskUsage: 0B/340GB, MemUsage: 0B/0B
```

### My deployment code

```yaml
timeZone: UTC
initPassword:
  enabled: true
  passwordSecret: hm-starrocks-secret
starrocksCluster:
  enabledBe: true
  enabledCn: true
starrocksFESpec:
  replicas: 3
  runAsNonRoot: true
  serviceAccount: hm-starrocks-service-account
  image:
    repository: harbor.hongbomiao.com/docker-hub-proxy-cache/starrocks/fe-ubuntu
    tag: 3.3.14
  storageSpec:
    name: fe
    storageClassName: production-hm-starrocks-storage-class
    storageSize: 10Gi
    logStorageSize: 0Gi
starrocksBeSpec:
  replicas: 3
  runAsNonRoot: true
  serviceAccount: hm-starrocks-service-account
  image:
    repository: harbor.hongbomiao.com/docker-hub-proxy-cache/starrocks/be-ubuntu
    tag: 3.3.14
  storageSpec:
    name: be
    storageClassName: production-hm-starrocks-storage-class
    storageSize: 500Gi
    logStorageSize: 0Gi
starrocksCnSpec:
  replicas: 5
  runAsNonRoot: true
  serviceAccount: hm-starrocks-service-account
  image:
    repository: harbor.hongbomiao.com/docker-hub-proxy-cache/starrocks/cn-ubuntu
    tag: 3.3.14
  storageSpec:
    name: cn
    storageClassName: production-hm-starrocks-storage-class
    storageSize: 500Gi
    logStorageSize: 0Gi
```

### Expected behavior (Required)

I expect DiskUsage being used.

### Real behavior (Required)

When I query Parquet file in S3 again, it still take same long time. Also, the DiskUsage is not being used.

Any guide would be appreciate, thanks! ☺️

### StarRocks version (Required)

`3.3.14-2ce6e68`
