### ISSUE TITLE
java.net.UnknownHostException during Cluster Snapshot upload

### ISSUE THREAD

**Issue by lobrandon1217** [StarRocks/starrocks#60009]
A `java.net.UnknownHostException` happens when the cluster snapshot is being uploaded to an internal S3-compliant service. The URL of the endpoint is being modified. In this example, the endpoint is `"aws.s3.endpoint":"https://service.data.company.com"` but the AWS SDK is complaining about the endpoint being `starrocks.service.data.company.com`

### Steps to reproduce the behavior (Required)
1. Create a storage volume (in this example, it is built-in)
```
describe storage volume builtin_storage_volume\G
*************************** 1. row ***************************
     Name: builtin_storage_volume
     Type: S3
IsDefault: true
 Location: s3://starrocks
   Params: {"aws.s3.access_key":"******","aws.s3.secret_key":"******","aws.s3.endpoint":"https://service.data.company.com","aws.s3.region":"","aws.s3.use_instance_profile":"false","aws.s3.use_aws_sdk_default_behavior":"false"}
  Enabled: true
  Comment: 
1 row in set (0.00 sec)
```
2. Enable snapshots
```
ADMIN SET AUTOMATED CLUSTER SNAPSHOT ON
```

### Expected behavior (Required)
Snapshot uploaded to S3 bucket.

### Real behavior (Required)
```
mysql> SELECT * FROM information_schema.cluster_snapshot_jobs;
+------------------------------------------+----------+---------------------+---------------+-------+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SNAPSHOT_NAME                            | JOB_ID   | CREATED_TIME        | FINISHED_TIME | STATE | DETAIL_INFO | ERROR_MESSAGE                                                                                                                                                                              |
+------------------------------------------+----------+---------------------+---------------+-------+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| automated_cluster_snapshot_1750189655708 | 11828821 | 2025-06-17 19:47:35 | NULL          | ERROR |             | upload image failed, err msg: Failed to copy local /opt/starrocks/fe/meta/image to s3://starrocks/4670ab84-aaaf-4606-a370-b762c206b7fe/meta/image/automated_cluster_snapshot_1750189655708 |
...
```

```
java.net.UnknownHostException: getFileStatus on s3://starrocks/4670ab84-aaaf-4606-a370-b762c206b7fe/meta/image/automated_cluster_snapshot_1750191657846: 
software.amazon.awssdk.core.exception.SdkClientException: Received an UnknownHostException when attempting to interact with a service. 
See cause for the exact endpoint that is failing to resolve. If this is happening on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long.:    software.amazon.awssdk.core.exception.SdkClientException: Received an UnknownHostException when attempting to interact with a service. 
See cause for the exact endpoint that is failing to resolve. If this is happening on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long.: starrocks.service.data.company.com
```

### StarRocks version (Required)
`3.5.0-10d7323`
