### ISSUE TITLE
query from iceberg table slow when use  enable_pipeline_engine

### ISSUE THREAD

**Issue by hongli-my** [StarRocks/starrocks#6248]
### Steps to reproduce the behavior (Required)
1.  create iceberg external table
```
CREATE EXTERNAL TABLE `iceberg_table1` (
  `order_id` bigint(20) NULL COMMENT "",
  `order_time` datetime NULL COMMENT ""
) ENGINE=ICEBERG
COMMENT "ICEBERG"
PROPERTIES (
"database" = "iceberg_db",
"table" = "table1",
"resource" = "iceberg0"
);
```
2.     enable enable_pipeline_engine or disable enable_pipeline_engine  to exec sql `select * from iceberg_table1`

`set enable_pipeline_engine=false`, use time : `0.53s`
`set enable_pipeline_engine=true`, use time: `5.75s`

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 starrocks version :  403eb7a

**Comment by hongli-my** [comment]
profile:
```
Query:
  Summary:
     - Query ID: 4744daf3-d65d-11ec-bc75-e69ff870d037
     - Start Time: 2022-05-18 11:47:45
     - End Time: 2022-05-18 11:47:50
     - Total: 5s67ms
     - Query Type: Query
     - Query State: EOF
     - StarRocks Version: UNKNOWN
     - User: root
     - Default Db: default_cluster:test
     - Sql Statement: select * from  iceberg_table1
  Planner:
     - Total: 217ms / 1
  Execution Profile 4744daf3-d65d-11ec-bc75-e69ff870d037:
     - ExecutionTotalTime: 4s838ms
    Fragment 0:
       - BackendNum: 1
       - InstanceNum: 1
       - MemoryLimit: 2.00 GB
       - PeakMemoryUsage: 78.09 KB
      Pipeline (id=0):
         - ActiveTime: 887.792us
         - DegreeOfParallelism: 1
         - DriverTotalTime: 4s838ms
         - OverheadTime: 887.792us
         - PendingTime: 4s837ms
           - InputEmptyTime: 4s837ms
             - FirstInputEmptyTime: 2s781ms
             - FollowupInputEmptyTime: 2s56ms
           - OutputFullTime: 0ns
           - PreconditionBlockTime: 0ns
         - ScheduleTime: 58.241us
         - TotalDegreeOfParallelism: 1
        RESULT_SINK:
          CommonMetrics:
             - CloseTime: 2.774us
             - OperatorTotalCostCpuTime: 0ns
             - OperatorTotalTime: 458.214us
             - PeakMemoryUsage: 0.00
             - PullChunkNum: 0
             - PullRowNum: 0
             - PullTotalTime: 0ns
             - PushChunkNum: 179
             - PushRowNum: 181
             - PushTotalTime: 455.217us
             - SetFinishedTime: 65ns
             - SetFinishingTime: 158ns
          UniqueMetrics:
        EXCHANGE_SOURCE (plan_node_id=1):
          CommonMetrics:
             - CloseTime: 564ns
             - OperatorTotalCostCpuTime: 0ns
             - OperatorTotalTime: 153.30us
             - PeakMemoryUsage: 0.00
             - PullChunkNum: 179
             - PullRowNum: 181
             - PullTotalTime: 148.453us
             - PushChunkNum: 0
             - PushRowNum: 0
             - PushTotalTime: 0ns
             - SetFinishedTime: 175ns
             - SetFinishingTime: 3.838us
          UniqueMetrics:
             - BytesPassThrough: 0.00
             - BytesReceived: 5.78 KB
             - DecompressChunkTime: 30.515us
             - DeserializeChunkTime: 294.587us
             - ReceiverProcessTotalTime: 465.88us
             - RequestReceived: 4
             - SenderTotalTime: 464.252us
             - SenderWaitLockTime: 1.678us
    Fragment 1:
       - BackendNum: 1
       - InstanceNum: 4
       - MemoryLimit: 8.00 GB
       - PeakMemoryUsage: 41.29 MB
      Pipeline (id=0):
         - ActiveTime: 4s28ms
           - __MAX_OF_ActiveTime: 4s836ms
           - __MIN_OF_ActiveTime: 2s779ms
         - DegreeOfParallelism: 1
         - DriverTotalTime: 4s30ms
           - __MAX_OF_DriverTotalTime: 4s837ms
           - __MIN_OF_DriverTotalTime: 2s783ms
         - OverheadTime: 4s28ms
           - __MAX_OF_OverheadTime: 4s836ms
           - __MIN_OF_OverheadTime: 2s779ms
         - PendingTime: 1.378ms
           - InputEmptyTime: 308.209us
             - FirstInputEmptyTime: 308.209us
             - FollowupInputEmptyTime: 0ns
           - OutputFullTime: 0ns
           - PreconditionBlockTime: 0ns
         - ScheduleTime: 1.158ms
         - TotalDegreeOfParallelism: 4
        EXCHANGE_SINK (plan_node_id=1):
          CommonMetrics:
             - CloseTime: 6.547us
             - OperatorTotalCostCpuTime: 0ns
             - OperatorTotalTime: 383.653us
             - PeakMemoryUsage: 0.00
             - PullChunkNum: 0
             - PullRowNum: 0
             - PullTotalTime: 0ns
             - PushChunkNum: 179
             - PushRowNum: 181
             - PushTotalTime: 285.79us
             - SetFinishedTime: 68ns
             - SetFinishingTime: 91.958us
          UniqueMetrics:
             - DestID: 1
             - DestFragments: 4744daf3d65d11ec-bc75e69ff870d03c
             - PartType: UNPARTITIONED
             - BytesPassThrough: 0.00
             - BytesSent: 5.78 KB
             - CompressTime: 88.740us
             - NetworkTime: 152.153us
             - OverallThroughput: 37.12743663787842 MB/sec
             - RequestSent: 4
             - SerializeChunkTime: 109.342us
             - ShuffleHashTime: 0ns
             - UncompressedBytes: 7.38 KB
             - WaitTime: 1.337ms
        CONNECTOR_SCAN (plan_node_id=0):
          CommonMetrics:
             - CloseTime: 244.466us
             - OperatorTotalCostCpuTime: 0ns
             - OperatorTotalTime: 4s27ms
               - __MAX_OF_OperatorTotalTime: 4s835ms
               - __MIN_OF_OperatorTotalTime: 2s779ms
             - PeakMemoryUsage: 0.00
             - PullChunkNum: 358
             - PullRowNum: 181
             - PullTotalTime: 4s27ms
               - __MAX_OF_PullTotalTime: 4s835ms
               - __MIN_OF_PullTotalTime: 2s779ms
             - PushChunkNum: 0
             - PushRowNum: 0
             - PushTotalTime: 0ns
             - SetFinishedTime: 268ns
             - SetFinishingTime: 216ns
          UniqueMetrics:
             - BytesRead: 79.92 KB
               - __MAX_OF_BytesRead: 20.16 KB
               - __MIN_OF_BytesRead: 455.00 B
             - ColumnConvertTime: 77.339us
             - ColumnReadTime: 3.593ms
               - __MAX_OF_ColumnReadTime: 7.663ms
               - __MIN_OF_ColumnReadTime: 348.348us
             - ExprFilterTime: 2.133us
             - IOCounter: 179
               - __MAX_OF_IOCounter: 45
               - __MIN_OF_IOCounter: 1
             - IOTime: 1s4ms
               - __MAX_OF_IOTime: 2s387ms
               - __MIN_OF_IOTime: 63.106ms
             - OpenFile: 0ns
             - ReaderInit: 1s6ms
               - __MAX_OF_ReaderInit: 2s389ms
               - __MIN_OF_ReaderInit: 63.201ms
             - RowsRead: 181
               - __MAX_OF_RowsRead: 46
               - __MIN_OF_RowsRead: 1
             - ScanFiles: 179
               - __MAX_OF_ScanFiles: 45
               - __MIN_OF_ScanFiles: 1
             - ScanRanges: 179
               - __MAX_OF_ScanRanges: 45
               - __MIN_OF_ScanRanges: 1
             - ScanTime: 7.395ms
               - __MAX_OF_ScanTime: 15.755ms
               - __MIN_OF_ScanTime: 714.308us
```
