### ISSUE TITLE
【Primary Table】The key data of the routine load JSON data becomes NULL

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#7460]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
CREATE TABLE primary_20cols_3rep
(k0 TINYINT NOT NULL, k1 DATE NOT NULL, k2 INT NOT NULL, k3 DATETIME NOT NULL, k4 BIGINT NOT NULL, k5 LARGEINT NOT NULL,
k6 BOOLEAN NOT NULL, k7 SMALLINT NOT NULL, k8 VARCHAR(21) NOT NULL, k9 STRING NOT NULL, v0 DECIMAL(8,4) NOT NULL,
v1 STRING NULL, v2 CHAR(126) NULL, v3 INT NULL, v4 DECIMAL(4,2) NULL, v5 DATETIME NULL, v6 DATETIME NULL, v7 STRING NULL,
v8 CHAR(40) NULL, v9 VARCHAR(165) NULL)
PRIMARY KEY(k0,k1,k2,k3,k4,k5,k6,k7,k8,k9)
DISTRIBUTED BY HASH(k0,k1,k2,k3,k4,k5,k6,k7,k8,k9) BUCKETS 5 PROPERTIES ("replication_num" = "3");
```
2. create topic in kafka and import data
3. routine load data
```
CREATE ROUTINE LOAD lcy on primary_20cols_3rep COLUMNS (k0,k1,k2,k3,k4,k5,k6,k7,k8,k9,v0,v1,v2,v3,v4,v5,v6,v7,v8,v9,__op),COLUMNS TERMINATED BY '\t' PROPERTIES ("desired_concurrent_number"="1","max_error_number"="100","max_batch_interval"="5","format"="json") FROM KAFKA ("kafka_broker_list"="172.26.92.141:9092","kafka_partitions"="0,1,2,3,4","kafka_offsets"="OFFSET_BEGINNING,OFFSET_BEGINNING,OFFSET_BEGINNING,OFFSET_BEGINNING,OFFSET_BEGINNING","kafka_topic"="test_json");
```

### Expected behavior (Required)
routine load success
### Real behavior (Required)
routine load failed
```
*************************** 2. row ***************************
                  Id: 3907656
                Name: lcy
          CreateTime: 2022-06-20 10:08:54
           PauseTime: NULL
             EndTime: NULL
              DbName: default_cluster:test_primary_table_rld8aa372a_f03c_11ec_883c_00163e0e550b
           TableName: primary_20cols_3rep
               State: RUNNING
      DataSourceType: KAFKA
      CurrentTaskNum: 1
       JobProperties: {"partitions":"*","partial_update":"false","columnToColumnExpr":"k0,k1,k2,k3,k4,k5,k6,k7,k8,k9,v0,v1,v2,v3,v4,v5,v6,v7,v8,v9,__op","maxBatchIntervalS":"5","whereExpr":"*","dataFormat":"json","timezone":"Asia/Shanghai","format":"json","json_root":"","strict_mode":"false","jsonpaths":"","desireTaskConcurrentNum":"1","maxErrorNum":"100","strip_outer_array":"false","currentTaskConcurrentNum":"1","maxBatchRows":"200000"}
DataSourceProperties: {"topic":"test_json","currentKafkaPartitions":"0,1,2,3,4","brokerList":"172.26.92.141:9092"}
    CustomProperties: {}
           Statistic: {"receivedBytes":1953,"errorRows":1,"committedTaskNum":0,"loadedRows":0,"loadRowsRate":0,"abortedTaskNum":1,"totalRows":1,"unselectedRows":0,"receivedBytesRate":0,"taskExecuteTimeMs":3008}
            Progress: {"0":"OFFSET_ZERO","1":"OFFSET_ZERO","2":"OFFSET_ZERO","3":"0","4":"OFFSET_ZERO"}
ReasonOfStateChanged:
        ErrorLogUrls: http://172.26.92.151:8538/api/_load_error_log?file=error_log_96397490df84014_93f68aaef268ea63
            OtherMsg:
2 rows in set (0.00 sec)
```
![image](https://user-images.githubusercontent.com/57162397/174513864-a9bcc28e-2c8f-4986-8df2-a59317e381b7.png)
![image](https://user-images.githubusercontent.com/57162397/174513908-dc18ca93-59ea-43d0-8565-bbadc41e0452.png)
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.3-RELEASE b202d93 |
+----------------------------+
```
