### ISSUE TITLE
[Bug] Unexpected runtime filter related metrics

### ISSUE THREAD

**Issue by liuyehcf** [StarRocks/starrocks#7538]
### Steps to reproduce the behavior (Required)

```sql
select count(*) from lineorder_flat group by LO_CUSTKEY;
```

### Real behavior (Required)

Here is part of profile of the above query

```
        AGGREGATE_BLOCKING_SOURCE (plan_node_id=3):
          CommonMetrics:
             - CloseTime: 10.420us
             - ConjunctsInputRows: 20.0K (20000)
             - ConjunctsOutputRows: 20.0K (20000)
             - JoinRuntimeFilterTime: 1.61us
```

1. Aggregate do not have having clause, so ConjunctsInputRows/ConjunctsOutputRows should be hidden
2. There is single table query, so runtime filter shouldn't be working, `JoinRuntimeFilterTime` must be wrong

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
