### ISSUE TITLE
Unnecessary retry in failed routine load scanning

### ISSUE THREAD

**Issue by rickif** [StarRocks/starrocks#8325]
## Enhancement
The routine load would retry when the scanner gets failure, which is useless since the error cannot be recovered by retrying.
The routine load job would be scheduled again and again, and the `abortedTaskNum` would continue to grow.
```
                  Id: 10014
                Name: rl_test_resume
          CreateTime: 2022-07-05 20:08:59
           PauseTime: NULL
             EndTime: NULL
              DbName: default_cluster:db0
           TableName: tbl_test_resume
               State: RUNNING
      DataSourceType: KAFKA
      CurrentTaskNum: 1
       JobProperties: {"partitions":"*","partial_update":"false","columnToColumnExpr":"key1,key2","maxBatchIntervalS":"10","whereExpr":"*","dataFormat":"json","timezone":"Asia/Shanghai","format":"json","json_root":"$.data","strict_mode":"false","jsonpaths":"","desireTaskConcurrentNum":"5","maxErrorNum":"0","strip_outer_array":"true","currentTaskConcurrentNum":"1","maxBatchRows":"200000"}
DataSourceProperties: {"topic":"topic_test_resume","currentKafkaPartitions":"0","brokerList":"172.26.92.155:9092"}
    CustomProperties: {}
           Statistic: {"receivedBytes":0,"errorRows":0,"committedTaskNum":0,"loadedRows":0,"loadRowsRate":0,"abortedTaskNum":72,"totalRows":0,"unselectedRows":0,"receivedBytesRate":0,"taskExecuteTimeMs":1}
            Progress: {"0":"29"}
ReasonOfStateChanged:
        ErrorLogUrls:
            OtherMsg:
1 row in set (0.00 sec)
```
## Version
main@8a4d61, 2.3-RC01, 2.2.2, 2.1.11
