### ISSUE TITLE
【usability stargo】stop cluster node should remind

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#8656]
1.
vim deploy-template.yaml
```
global:
    user: "starrocks"
    ssh_port: 22

fe_servers:
  - host: 192.168.88.83
    ssh_port: 22
    http_port: 8032
    rpc_port: 9022
    query_port: 9032
    edit_log_port: 9012
    deploy_dir: /opt/starrocks2/fe
    meta_dir: /data/starrocks2/fe/meta
    log_dir: /data/starrocks2/fe/log
    priority_networks: 192.168.88.0/24
    config:
      sys_log_level: "INFO"

be_servers:
  - host: 192.168.88.83
    ssh_port: 22
    be_port: 9062
    webserver_port: 8042
    heartbeat_service_port: 9052
    brpc_port: 8062
    deploy_dir : /opt/starrocks2/be
    storage_dir: /data/starrocks2/be/storage
    log_dir: /data/starrocks2/be/log
    priority_networks: 192.168.88.0/24
    config:
      create_tablet_worker_count: 3
```
2.
The cluster has been deploy
3.
```
./stargo cluster stop lcy_sr ID
```

Expected behavior (Required)
stop cluster node should remind

Real behavior (Required)
The command to stop the cluster should be prompted for missing nodes
![rd6F6feywy](https://user-images.githubusercontent.com/57162397/178749578-45d21459-e09f-4caa-bcb4-0081a37c899c.png)
