### ISSUE TITLE
No error in routine load when there's invalid JSON message

### ISSUE THREAD

**Issue by rickif** [StarRocks/starrocks#8790]
### Steps to reproduce the behavior (Required)
1. Create table
```
CREATE TABLE `tbl_simple` (
  `key1` int(11) NULL COMMENT "",
  `key2` int(11) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`key1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`key1`) BUCKETS 3
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);
```
1. Prepare some data in Kafka
Some valid JSON messages and some invalid messages.
```
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2
{"key1":1,"key2":2
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
```
3. Create routine load
```
CREATE ROUTINE LOAD rl_simple ON tbl_simple COLUMNS (key1, key2) PROPERTIES ( "format" = "json") FROM KAFKA ( "kafka_broker_list" = "xxx", "kafka_topic" = "topic-invalid-json", "kafka_partitions" = "0", "kafka_offsets" = "OFFSET_BEGINNING" );
``` 

### Expected behavior (Required)
The routine load is paused due to invalid message.
```
mysql> show routine load\G;
*************************** 1. row ***************************
                  Id: 10264
                Name: rl_simple
          CreateTime: 2022-07-15 21:19:53
           PauseTime: 2022-07-15 21:20:07
             EndTime: NULL
              DbName: default_cluster:db0
           TableName: tbl_simple
               State: PAUSED
      DataSourceType: KAFKA
      CurrentTaskNum: 0
       JobProperties: {"partitions":"*","partial_update":"false","columnToColumnExpr":"key1,key2","maxBatchIntervalS":"10","whereExpr":"*","dataFormat":"json","timezone":"Asia/Shanghai","format":"json","json_root":"","strict_mode":"false","jsonpaths":"","desireTaskConcurrentNum":"5","maxErrorNum":"0","strip_outer_array":"false","currentTaskConcurrentNum":"1","maxBatchRows":"200000"}
DataSourceProperties: {"topic":"topic-invalid-json","currentKafkaPartitions":"0","brokerList":"172.26.92.155:9092"}
    CustomProperties: {}
           Statistic: {"receivedBytes":416,"errorRows":2,"committedTaskNum":1,"loadedRows":20,"loadRowsRate":0,"abortedTaskNum":0,"totalRows":22,"unselectedRows":0,"receivedBytesRate":0,"taskExecuteTimeMs":3007}
            Progress: {"0":"21"}
ReasonOfStateChanged: ErrorReason{errCode = 102, msg='current error rows is more than max error num'}
        ErrorLogUrls: http://172.26.92.139:8082/api/_load_error_log?file=error_log_c43060a806f449ce_b6f50dca8c44c5a7
            OtherMsg:
1 row in set (0.00 sec)
```
### Real behavior (Required)
The routine load runs without pause.
```
mysql> show routine load\G;
*************************** 1. row ***************************
                  Id: 10263
                Name: rl_simple
          CreateTime: 2022-07-15 20:43:43
           PauseTime: NULL
             EndTime: NULL
              DbName: default_cluster:db0
           TableName: tbl_simple
               State: RUNNING
      DataSourceType: KAFKA
      CurrentTaskNum: 1
       JobProperties: {"partitions":"*","partial_update":"false","columnToColumnExpr":"key1,key2","maxBatchIntervalS":"10","whereExpr":"*","dataFormat":"json","timezone":"Asia/Shanghai","format":"json","json_root":"","strict_mode":"false","jsonpaths":"","desireTaskConcurrentNum":"5","maxErrorNum":"0","strip_outer_array":"false","currentTaskConcurrentNum":"1","maxBatchRows":"200000"}
DataSourceProperties: {"topic":"topic-invalid-json","currentKafkaPartitions":"0","brokerList":"172.26.92.155:9092"}
    CustomProperties: {}
           Statistic: {"receivedBytes":416,"errorRows":0,"committedTaskNum":1,"loadedRows":20,"loadRowsRate":0,"abortedTaskNum":0,"totalRows":20,"unselectedRows":0,"receivedBytesRate":0,"taskExecuteTimeMs":3008}
            Progress: {"0":"21"}
ReasonOfStateChanged:
        ErrorLogUrls:
            OtherMsg:
1 row in set (0.01 sec)
```
### StarRocks version (Required)
2.3-rc02, main@bd6de9aba, 2.2.2, 2.1.11
