### ISSUE TITLE
[BugFix] Profile incomplete

### ISSUE THREAD

**Issue by liuyehcf** [StarRocks/starrocks#8984]
### Steps to reproduce the behavior (Required)

```sql
select level, count(*) uv from ( select lo_orderkey, window_funnel(3600000, lo_orderdate, 0, [lo_linenumber=1, lo_linenumber=2]) as level from ssb_100g.lineorder group by lo_orderkey ) AS x group by level
```

### Real behavior (Required)

```
Query:
  Summary:
     - Query ID: 5c7aa354-08bf-11ed-a048-00163e12238b
     - Start Time: 2022-07-21 14:35:50
     - End Time: 2022-07-21 14:35:57
     - Total: 6s866ms
     - Query Type: Query
     - Query State: EOF
     - StarRocks Version: UNKNOWN-dd84b5fda
     - User: root
     - Default Db: 
     - Sql Statement: select level, count(*) uv from ( select lo_orderkey, window_funnel(3600000, lo_orderdate, 0, [lo_linenumber=1, lo_linenumber=2]) as level from ssb_100g.lineorder group by lo_orderkey ) AS x group by level
     - QueryCpuCost: 3m31s
     - QueryMemCost: 4.226GB
     - Variables: parallel_fragment_exec_instance_num=1,pipeline_dop=0
     - Collect Profile Time: 2s2ms
  Planner:
     - Total: 13ms / 1
  Execution Profile 5c7aa354-08bf-11ed-a048-00163e12238b:
     - ExecutionTotalTime: 6s844ms
    Fragment 0:
       - BackendNum: 1
       - InstanceNum: 1
       - PeakMemoryUsage: 20.95 KB
       - QueryMemoryLimit: 81.48 GB
      Pipeline (id=0):
         - ActiveTime: 20.630us
         - BlockByInputEmpty: 16
           - __MAX_OF_BlockByInputEmpty: 16
           - __MIN_OF_BlockByInputEmpty: 0
         - BlockByOutputFull: 0
         - BlockByPrecondition: 0
         - DegreeOfParallelism: 32
         - DriverTotalTime: 6s844ms
         - OverheadTime: 20.630us
         - PendingTime: 6s843ms
           - InputEmptyTime: 6s843ms
             - FirstInputEmptyTime: 6s843ms
             - FollowupInputEmptyTime: 105.928us
           - OutputFullTime: 0ns
           - PendingFinishTime: 0ns
           - PreconditionBlockTime: 0ns
         - ScheduleCount: 48
         - ScheduleTime: 808.935us
         - TotalDegreeOfParallelism: 32
         - YieldByTimeLimit: 0
        RESULT_SINK:
          CommonMetrics:
             - CloseTime: 1.179us
             - OperatorTotalTime: 6.115us
             - PeakMemoryUsage: 0.00 
             - PullChunkNum: 0
             - PullRowNum: 0
             - PullTotalTime: 0ns
             - PushChunkNum: 2
               - __MAX_OF_PushChunkNum: 2
               - __MIN_OF_PushChunkNum: 0
             - PushRowNum: 2
               - __MAX_OF_PushRowNum: 2
               - __MIN_OF_PushRowNum: 0
             - PushTotalTime: 4.747us
             - SetFinishedTime: 37ns
             - SetFinishingTime: 150ns
          UniqueMetrics:
        EXCHANGE_SOURCE (plan_node_id=7):
          CommonMetrics:
             - CloseTime: 6.324us
             - OperatorTotalTime: 13.629us
             - PeakMemoryUsage: 0.00 
             - PullChunkNum: 3
               - __MAX_OF_PullChunkNum: 3
               - __MIN_OF_PullChunkNum: 0
             - PullRowNum: 2
               - __MAX_OF_PullRowNum: 2
               - __MIN_OF_PullRowNum: 0
             - PullTotalTime: 1.531us
             - PushChunkNum: 0
             - PushRowNum: 0
             - PushTotalTime: 0ns
             - SetFinishedTime: 68ns
             - SetFinishingTime: 5.704us
          UniqueMetrics:
             - BytesPassThrough: 0.00 
             - BytesReceived: 58.00 B
             - ClosureBlockTime: 0ns
             - DecompressChunkTime: 3.8us
             - DeserializeChunkTime: 42.603us
             - ReceiverProcessTotalTime: 66.788us
             - RequestReceived: 3
             - SenderTotalTime: 66.116us
             - SenderWaitLockTime: 1.142us
    Fragment 1:
       - BackendNum: 3
       - InstanceNum: 3
       - PeakMemoryUsage: 310.68 KB
       - QueryMemoryLimit: 244.45 GB
       - __MAX_OF_PeakMemoryUsage: 131.55 KB
       - __MIN_OF_PeakMemoryUsage: 51.93 KB
      Pipeline (id=1):
         - ActiveTime: 19.968us
         - BlockByInputEmpty: 0
         - BlockByOutputFull: 0
         - BlockByPrecondition: 0
         - DegreeOfParallelism: 32
         - DriverTotalTime: 6s837ms
         - OverheadTime: 19.968us
         - PendingTime: 6s836ms
           - InputEmptyTime: 6s835ms
             - FirstInputEmptyTime: 6s835ms
             - FollowupInputEmptyTime: 0ns
           - OutputFullTime: 0ns
           - PendingFinishTime: 445.702us
           - PreconditionBlockTime: 0ns
         - ScheduleCount: 96
         - ScheduleTime: 1.350ms
         - TotalDegreeOfParallelism: 96
         - YieldByTimeLimit: 0
        EXCHANGE_SINK (plan_node_id=7):
          CommonMetrics:
             - CloseTime: 991ns
             - OperatorTotalTime: 16.593us
             - PeakMemoryUsage: 0.00 
             - PullChunkNum: 0
             - PullRowNum: 0
             - PullTotalTime: 0ns
             - PushChunkNum: 2
               - __MAX_OF_PushChunkNum: 1
               - __MIN_OF_PushChunkNum: 0
             - PushRowNum: 2
               - __MAX_OF_PushRowNum: 1
               - __MIN_OF_PushRowNum: 0
             - PushTotalTime: 364ns
             - SetFinishedTime: 47ns
             - SetFinishingTime: 15.188us
          UniqueMetrics:
             - DestID: 7
             - DestFragments: 5c7aa35408bf11ed-a04800163e122392
             - PartType: UNPARTITIONED
             - BytesPassThrough: 0.00 
             - BytesSent: 58.00 B
               - __MAX_OF_BytesSent: 33.00 B
               - __MIN_OF_BytesSent: 0.00 
             - CompressTime: 177ns
             - NetworkTime: 1.687ms
             - OverallThroughput: 22.7451171875 KB/sec
               - __MAX_OF_OverallThroughput: 12.2060546875 KB/sec
               - __MIN_OF_OverallThroughput: 0.0 /sec
             - RequestSent: 2
               - __MAX_OF_RequestSent: 1
               - __MIN_OF_RequestSent: 0
             - SerializeChunkTime: 115ns
             - ShuffleHashTime: 0ns
             - UncompressedBytes: 66.00 B
               - __MAX_OF_UncompressedBytes: 33.00 B
               - __MIN_OF_UncompressedBytes: 0.00 
             - WaitTime: 399.829us
        AGGREGATE_BLOCKING_SOURCE (plan_node_id=6):
          CommonMetrics:
             - CloseTime: 12.321us
             - JoinRuntimeFilterEvaluate: 0
             - JoinRuntimeFilterInputRows: 0
             - JoinRuntimeFilterOutputRows: 0
             - JoinRuntimeFilterTime: 0ns
             - OperatorTotalTime: 13.269us
             - PeakMemoryUsage: 0.00 
             - PullChunkNum: 2
               - __MAX_OF_PullChunkNum: 1
               - __MIN_OF_PullChunkNum: 0
             - PullRowNum: 2
               - __MAX_OF_PullRowNum: 1
               - __MIN_OF_PullRowNum: 0
             - PullTotalTime: 763ns
             - PushChunkNum: 0
             - PushRowNum: 0
             - PushTotalTime: 0ns
             - SetFinishedTime: 76ns
             - SetFinishingTime: 106ns
          UniqueMetrics:
      Pipeline (id=0):
         - ActiveTime: 59.655us
         - BlockByInputEmpty: 127
           - __MAX_OF_BlockByInputEmpty: 64
           - __MIN_OF_BlockByInputEmpty: 0
         - BlockByOutputFull: 0
         - BlockByPrecondition: 0
         - DegreeOfParallelism: 32
         - DriverTotalTime: 6s838ms
         - OverheadTime: 59.655us
         - PendingTime: 6s835ms
           - InputEmptyTime: 6s835ms
             - FirstInputEmptyTime: 6s810ms
             - FollowupInputEmptyTime: 24.845ms
               - __MAX_OF_FollowupInputEmptyTime: 1s257ms
               - __MIN_OF_FollowupInputEmptyTime: 0ns
           - OutputFullTime: 0ns
           - PendingFinishTime: 0ns
           - PreconditionBlockTime: 0ns
         - ScheduleCount: 223
           - __MAX_OF_ScheduleCount: 96
           - __MIN_OF_ScheduleCount: 1
         - ScheduleTime: 3.221ms
         - TotalDegreeOfParallelism: 96
         - YieldByTimeLimit: 0
        AGGREGATE_BLOCKING_SINK (plan_node_id=6):
          CommonMetrics:
             - CloseTime: 6.328us
             - OperatorTotalTime: 20.931us
             - PeakMemoryUsage: 8.10 KB
               - __MAX_OF_PeakMemoryUsage: 4.05 KB
               - __MIN_OF_PeakMemoryUsage: 0.00 
             - PullChunkNum: 0
             - PullRowNum: 0
             - PullTotalTime: 0ns
             - PushChunkNum: 192
               - __MAX_OF_PushChunkNum: 96
               - __MIN_OF_PushChunkNum: 0
             - PushRowNum: 192
               - __MAX_OF_PushRowNum: 96
               - __MIN_OF_PushRowNum: 0
             - PushTotalTime: 12.795us
             - SetFinishedTime: 40ns
             - SetFinishingTime: 1.765us
          UniqueMetrics:
             - GroupingKeys: 19: window_funnel
             - AggregateFunctions: count(20: count)
             - AggComputeTime: 3.293us
             - ExprComputeTime: 2.969us
             - ExprReleaseTime: 5.266us
             - GetResultsTime: 341ns
             - HashTableSize: 2
               - __MAX_OF_HashTableSize: 1
               - __MIN_OF_HashTableSize: 0
             - InputRowCount: 192
               - __MAX_OF_InputRowCount: 96
               - __MIN_OF_InputRowCount: 0
             - PassThroughRowCount: 0
             - ResultAggAppendTime: 25ns
             - ResultGroupByAppendTime: 17ns
             - ResultIteratorTime: 76ns
             - RowsReturned: 0
             - StreamingTime: 0ns
        EXCHANGE_SOURCE (plan_node_id=5):
          CommonMetrics:
             - CloseTime: 8.856us
             - JoinRuntimeFilterEvaluate: 0
             - JoinRuntimeFilterInputRows: 0
             - JoinRuntimeFilterOutputRows: 0
             - JoinRuntimeFilterTime: 0ns
             - OperatorTotalTime: 30.763us
             - PeakMemoryUsage: 0.00 
             - PullChunkNum: 192
               - __MAX_OF_PullChunkNum: 96
               - __MIN_OF_PullChunkNum: 0
             - PullRowNum: 192
               - __MAX_OF_PullRowNum: 96
               - __MIN_OF_PullRowNum: 0
             - PullTotalTime: 10.608us
             - PushChunkNum: 0
             - PushRowNum: 0
             - PushTotalTime: 0ns
             - SetFinishedTime: 84ns
             - SetFinishingTime: 11.213us
          UniqueMetrics:
             - BytesPassThrough: 2.06 KB
               - __MAX_OF_BytesPassThrough: 1.03 KB
               - __MIN_OF_BytesPassThrough: 0.00 
             - BytesReceived: 3.63 KB
               - __MAX_OF_BytesReceived: 2.06 KB
               - __MIN_OF_BytesReceived: 0.00 
             - ClosureBlockTime: 0ns
             - DecompressChunkTime: 30.532us
             - DeserializeChunkTime: 231.113us
             - ReceiverProcessTotalTime: 551.579us
             - RequestReceived: 131
               - __MAX_OF_RequestReceived: 65
               - __MIN_OF_RequestReceived: 1
             - SenderTotalTime: 546.296us
             - SenderWaitLockTime: 20.84us
    Fragment 2:
       - BackendNum: 3
      Instance 5c7aa354-08bf-11ed-a048-00163e12238c (host=TNetworkAddress(hostname:172.26.194.223, port:9960)):
      Instance 5c7aa354-08bf-11ed-a048-00163e12238d (host=TNetworkAddress(hostname:172.26.194.221, port:9960)):
      Instance 5c7aa354-08bf-11ed-a048-00163e12238e (host=TNetworkAddress(hostname:172.26.194.222, port:9960)):
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
